'use client';
import {assetUrl} from './atlas/runtime';
import {useState,useEffect,useMemo,useRef} from 'react';
import {AnimatePresence,motion,MotionConfig,useReducedMotion} from 'framer-motion';
import dynamic from 'next/dynamic';
import {Stethoscope,Activity,ArrowUpRight, Bone,Brain, Check, ChevronRight, CircleHelp, Crosshair, Eye, Heart, Layers, Maximize2, Minus, Move, Pause, Play, Plus, RotateCcw, Search, Share2, ShieldCheck, Sparkles, X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {parts,systems,System,anatomySource,Part} from './atlas/data';
import PainJournal from './atlas/PainJournal';
import GuidedPain from './atlas/GuidedPain';
import {education} from './atlas/education';
import PanelResize,{usePanelWidths} from './atlas/PanelResize';
import {PainDraft,PainPoint,painRegions,detectPainRegion} from './atlas/pain';
import {loadAtlas,describeMesh,category,MeshPart,meshSystem,referenceParts,isAdapted,provenance} from './atlas/model';
const Scene=dynamic(()=>import('./atlas/Scene'),{ssr:false,loading:()=> <div className="model-loading">Preparing your atlas…</div>});
const initial:System[]=systems.map(s=>s[0]);
const regions=painRegions;
const regionParts:Record<string,string[]>={Head:['brain','eyes','skull'],Neck:['nerves','thyroid','spine'],Shoulder:['deltoid','clavicle','nerves'],Chest:['heart','lungs','ribs','pectoral'],'Lower back':['spine','backmuscle','nerves','kidneys'],'Upper back':['spine','backmuscle','ribs','nerves'],Back:['spine','backmuscle','nerves','kidneys'],Abdomen:['stomach','intestines','liver','kidneys'],Pelvis:['bladder','pelvis'],Arm:['biceps','humerus','nerves'],Hand:['hand','nerves'],Leg:['quadriceps','femur','nerves','veins'],Knee:['patella','femur','quadriceps'],Foot:['foot','nerves']};
export default function Home(){
 const {widths,resize}=usePanelWidths();const reduceMotion=useReducedMotion();const captureRef=useRef<(()=>string)|null>(null);const [painArea,setPainArea]=useState<string|null>(null);
 const [sex,setSex]=useState('male'),[visible,setVisible]=useState<System[]>(initial),[selected,setSelected]=useState('pectoral'),[query,setQuery]=useState(''),[tab,setTab]=useState('explore'),[opacity,setOpacity]=useState(100),[rotate,setRotate]=useState(false),[view,setView]=useState('Front'),[reset,setReset]=useState(0),[zoom,setZoom]=useState(0),[labels,setLabels]=useState(true),[region,setRegion]=useState('Chest'),[quality,setQuality]=useState('Aching'),[severity,setSeverity]=useState(4),[duration,setDuration]=useState('Today'),[notes,setNotes]=useState(''),[result,setResult]=useState(false),[urgent,setUrgent]=useState(false),[toast,setToast]=useState(''),[info,setInfo]=useState(false),[shareOpen,setShareOpen]=useState(false);
 const [sourceParts,setSourceParts]=useState<MeshPart[]>([]),[adapted,setAdapted]=useState(true);
 const [painPoint,setPainPoint]=useState<PainPoint|null>(null),[painFocus,setPainFocus]=useState<{region:string;nonce:number}|null>(null),[marking,setMarking]=useState(false);
 const painDraft=useMemo<PainDraft>(()=>({sex,region,quality,severity,duration,notes,urgent,point:painPoint}),[sex,region,quality,severity,duration,notes,urgent,painPoint]);
 function focusPain(area:string){setView(/back/i.test(area)?'Back':'Front');setPainArea(area);if(painPoint?.region!==area)setPainPoint(null);setRegion(area);setTab('pain');setRotate(false);setMarking(true);setVisible(['integumentary']);setOpacity(100);setPainFocus({region:area,nonce:Date.now()});}
 function restorePain(d:PainDraft){setSex(d.sex);setRegion(d.region);setQuality(d.quality);setSeverity(d.severity);setDuration(d.duration);setNotes(d.notes);setUrgent(d.urgent);setPainPoint(d.point);setResult(false);setMarking(false);if(d.point){setVisible(['integumentary']);setPainFocus({region:d.region,nonce:Date.now()});}}
 const rawParts=useMemo(()=>referenceParts(sourceParts,adapted),[sourceParts,adapted]);
 const realParts=useMemo(()=>rawParts.map(p=>describeMesh(p,sex)),[rawParts,sex]);
 const allParts=[...parts,...realParts];
 const categoryCounts=Object.fromEntries(systems.map(([id])=>[id,rawParts.filter(p=>meshSystem(p)===id).length])) as Record<System,number>;
 const adaptedCounts=Object.fromEntries(systems.map(([id])=>[id,rawParts.filter(p=>meshSystem(p)===id&&isAdapted(p)).length])) as Record<System,number>;
 const countLabel=(id:System)=>rawParts.length?`${categoryCounts[id]} elements${adaptedCounts[id]?` · ${adaptedCounts[id]} adapted`:''}`:'Loading elements';
 const selectedPart=allParts.find(p=>p.id===selected)||parts[0],system=systems.find(s=>s[0]===selectedPart.system)!;const learning=education(selectedPart,rawParts.find(p=>p.id===selected));
 useEffect(()=>{let active=true;loadAtlas(sex).then(data=>{if(active){setSourceParts(data.parts);}}).catch(()=>setToast('The anatomy catalog could not load. Reload to retry.'));return()=>{active=false;};},[sex]);
 const eligible=parts.filter(p=>(!p.sex||p.sex===sex)&&(!rawParts.length||rawParts.some(m=>category(m)===p.id))),matches=[...eligible,...realParts].filter(p=>(!p.sex||p.sex===sex)).filter(p=>(p.name+' '+p.system+' '+p.region).toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{
 const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!context?.registerTool)return;
 const lifecycle=new AbortController();
 try{Promise.resolve(context.registerTool({name:'configure_anatomy_view',description:'Select a male or female anatomy preset and focus a named structure in the visible atlas.',inputSchema:{type:'object',properties:{sex:{type:'string',enum:['male','female']},structureId:{type:'string',enum:parts.map(p=>p.id)}},required:['sex','structureId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const args=input as {sex:string;structureId:string};const part=parts.find(p=>p.id===args?.structureId);if(!part||!['male','female'].includes(args.sex)||(part.sex&&part.sex!==args.sex))throw new Error('Choose a valid structure for this anatomy preset.');const atlas=await loadAtlas(args.sex);if(!atlas.parts.some(p=>category(p)===part.id))throw new Error('This structure is not modeled in this reference.');setAdapted(true);setSex(args.sex);setSelected(part.id);setVisible([part.system]);setTab('explore');await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {sex:args.sex,selected:part.id,visibleSystems:[part.system]};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{try{const data=JSON.parse(decodeURIComponent(location.hash.slice(1)));if(typeof data.adapted==='boolean')setAdapted(data.adapted);if(data.sex==='female'||data.sex==='male')setSex(data.sex);if(parts.some(p=>p.id===data.part)){setSelected(data.part);setVisible([parts.find(p=>p.id===data.part)!.system]);}else if(typeof data.part==='string'){loadAtlas(data.sex==='female'?'female':'male').then(atlas=>{const p=atlas.parts.find(p=>p.id===data.part);if(p){const desc=describeMesh(p,data.sex);setSelected(desc.id);setVisible([desc.system]);}}).catch(()=>{});}if(regions.includes(data.region)){setRegion(data.region);setTab('pain');if(['Aching','Sharp','Burning','Tingling','Throbbing','Cramping'].includes(data.quality))setQuality(data.quality);if(Number.isInteger(data.severity)&&data.severity>=1&&data.severity<=10)setSeverity(data.severity);}}catch{}},[]);
 function select(id:string){const p=allParts.find(p=>p.id===id);if(!p)return;if(rawParts.length&&!rawParts.some(m=>m.id===id||category(m)===id)){setToast('This structure is not modeled in the selected reference.');return;}setSelected(id);setVisible(v=>v.includes(p.system)?v:[...v,p.system]);if(tab==='pain'){if(regions.includes(p.region)&&!painPoint)setRegion(p.region);setResult(false);}}
 function changeSex(value:string){setPainArea(null);setPainPoint(null);setMarking(false);setPainFocus(null);setSex(value);setSourceParts([]);setAdapted(true);setSelected(value==='female'?'skin':'pectoral');setVisible(initial);setOpacity(100);setView('Front');setZoom(0);setReset(r=>r+1);setResult(false);}
 function showPainAnatomy(area:string){const ids=(regionParts[area]||[]).filter(id=>rawParts.some(m=>category(m)===id));setPainArea(area);setVisible(['integumentary',...new Set(ids.map(id=>parts.find(p=>p.id===id)!.system))]);setSelected(ids[0]||'skin');setOpacity(70);}
 function toggle(id:System){setVisible(v=>v.includes(id)?v.filter(s=>s!==id):[...v,id]);}
 function analyze(){const area=painPoint?.region||detectPainRegion(notes)||region;setRegion(area);if(!painPoint){focusPain(area);}let ids=regionParts[area]||['nerves'];if(quality==='Tingling'||quality==='Burning')ids=[...new Set([...ids,'nerves'])];if(area==='Pelvis')ids=[...ids,...(sex==='female'?['uterus','ovaries']:['prostate','testes'])];ids=ids.filter(id=>rawParts.some(m=>category(m)===id));if(ids.length){if(painPoint)setVisible([...new Set(ids.map(id=>parts.find(p=>p.id===id)!.system))]);setSelected(ids[0]);}else{setVisible(['integumentary']);setSelected('skin');setToast('No matching structures are modeled for this region. Showing body surface.');}setResult(true);}
 async function share(){const data=tab==='pain'?{sex,adapted,part:selected,region,quality,severity}:{sex,adapted,part:selected};const url=location.origin+location.pathname+'#'+encodeURIComponent(JSON.stringify(data));try{await navigator.clipboard.writeText(url);setToast('Link copied. Notes and emergency answers are excluded.');setShareOpen(false);}catch{setToast('Clipboard unavailable. Use the link field to copy manually.');}return url;}
 const shareURL=typeof window==='undefined'?'':window.location.origin+window.location.pathname+'#'+encodeURIComponent(JSON.stringify(tab==='pain'?{sex,adapted,part:selected,region,quality,severity}:{sex,adapted,part:selected}));
 return <MotionConfig reducedMotion="user" transition={{duration:.28,ease:[.22,1,.36,1]}}><main className="atlas-app">
 <header className="topbar"><a className="brand" href={assetUrl("/")} aria-label="PreDoc home"><span className="brandmark"><Stethoscope size={24}/></span><span>Pre<span className="brand-light">Doc</span><small>KNOW YOUR BODY</small></span></a><nav><button className={tab==='explore'?'nav-active':''} onClick={()=>setTab('explore')}>Anatomy explorer</button><button className={tab==='pain'?'nav-active':''} onClick={()=>setTab('pain')}>Pain explorer <span className="new">BETA</span></button></nav><div className="top-actions"><button className="icon-button" aria-label="About this atlas" onClick={()=>setInfo(v=>!v)}><CircleHelp size={19}/></button><button className="share-button" onClick={()=>setShareOpen(true)}><Share2 size={15}/> Share view</button></div></header>
 <div className="workspace" style={{'--left-width':widths.left+'px','--right-width':widths.right+'px'} as React.CSSProperties}>
 <motion.aside initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} className="left-panel"><div className="panel-top"><span className="eyebrow">PREDOC / ANATOMY</span><h1>Layers of life<span>.</span></h1><p>Real anatomy. A deeper perspective.</p></div>
 <Tabs value={sex} onValueChange={changeSex}><TabsList className="sex-tabs"><TabsTrigger value="male">♂ &nbsp; Male</TabsTrigger><TabsTrigger value="female">♀ &nbsp; Female</TabsTrigger></TabsList></Tabs>
 {sex==='female'&&<div className="female-reference"><strong>Female reference anatomy</strong><p>Female source anatomy with optional fitted reference additions. Adapted bones are male-derived; added leg muscles come from another female donor. Upper-body muscles remain incomplete.</p><label className="adapted-control"><span>Include adapted anatomy<small>180 bone pieces + 76 female-donor muscles</small></span><Switch checked={adapted} onCheckedChange={value=>{setAdapted(value);if(!value&&sourceParts.some(p=>p.id===selected&&isAdapted(p)))setSelected('skin');}} aria-label="Include adapted reference anatomy"/></label><div className="female-presets"><button onClick={()=>{setVisible(['skeletal']);setSelected('pelvis');}}>Skeleton</button><button onClick={()=>{setVisible(['skeletal','muscular']);setSelected('femur');}}>Bones & muscles</button><button onClick={()=>{setVisible(['integumentary']);setSelected('skin');setOpacity(100);}}>Body surface</button><button onClick={()=>{setVisible(['integumentary','respiratory','digestive','cardiovascular','urinary']);setSelected('heart');}}>Internal organs</button><button onClick={()=>{setVisible(['reproductive','urinary','skeletal']);setSelected('uterus');}}>Pelvic anatomy</button></div></div>}
 <label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a structure…" aria-label="Search anatomy"/><span>⌕</span></label>
 <div className="section-heading"><h2>{query?'SEARCH RESULTS':'BODY SYSTEMS'}</h2><button onClick={()=>setVisible(visible.length===systems.length?[]:systems.map(s=>s[0]))}>{visible.length===systems.length?'Hide all':'Show all'}</button></div>
 <div className="systems-list">{query?<div className="search-results">{matches.length?matches.slice(0,120).map(p=><button key={p.id} onClick={()=>select(p.id)}><span>{p.name}<small>{p.region} · {p.system}</small></span><ChevronRight size={15}/></button>):<p>No structures match “{query}”. Try a body region or system.</p>}</div>:systems.map(([id,name,color,desc])=><motion.div layout className={'system-row '+(visible.includes(id)?'is-visible':'')} key={id}><button className="system-main" disabled={rawParts.length>0&&!realParts.some(p=>p.system===id)} onClick={()=>{setVisible([id]);setSelected(eligible.find(p=>p.system===id)?.id||realParts.find(p=>p.system===id)?.id||'skin');}} title={'Focus on '+name}><span className="system-icon" style={{color}}>{id==='skeletal'?<Bone size={19}/>:id==='nervous'?<Brain size={19}/>:id==='cardiovascular'?<Heart size={19}/>:id==='sensory'?<Eye size={19}/>:<Activity size={19}/>}</span><span>{name}<small>{desc}</small><span className="element-count">{countLabel(id)}</span>{rawParts.length>0&&!realParts.some(p=>p.system===id)&&<em>Not in this reference</em>}</span></button><Switch disabled={rawParts.length>0&&!realParts.some(p=>p.system===id)} checked={visible.includes(id)} onCheckedChange={()=>toggle(id)} aria-label={'Show '+name} size="sm"/></motion.div>)}</div>
 <div className="left-bottom"><div className="section-heading"><h2>LAYER OPACITY</h2><span>{opacity}%</span></div><Slider aria-label="Layer opacity" min={15} max={100} value={[opacity]} onValueChange={v=>setOpacity(v[0])}/><div className="subtle-label"><span>Transparent</span><span>Solid</span></div><div className="education-note"><ShieldCheck size={17}/><span>Reference anatomy<br/>For education, not diagnosis.</span></div></div>
 </motion.aside><PanelResize side="left" width={widths.left} onResize={w=>resize('left',w)}/>
 <section className="viewport"><div className="medical-emblem-wash" aria-hidden="true"><svg viewBox="0 0 300 400" fill="none"><circle cx="150" cy="194" r="134" stroke="currentColor" strokeWidth="1"/><circle cx="150" cy="194" r="115" stroke="currentColor" strokeWidth="1" strokeDasharray="2 12"/><path d="M150 55V348" stroke="currentColor" strokeWidth="9" strokeLinecap="round"/><circle cx="150" cy="48" r="12" fill="currentColor"/><path d="M167 90C225 92 228 140 166 155L126 166C72 181 82 224 147 237C213 250 212 281 157 301L135 310" stroke="currentColor" strokeWidth="14" strokeLinecap="round"/><path d="M167 80L145 90L167 103Z" fill="currentColor"/></svg></div><div className="viewport-heading"><div><span className="eyebrow">ANATOMY EXPLORER</span><h2>{sex==='male'?'Male':'Female'} anatomy <span>/ {visible.length===1?systems.find(s=>s[0]===visible[0])?.[1]:(sex==='female'?'Partial reference':'Full body')}</span></h2></div><span className="model-badge"><span/> LIVE 3D</span></div>
 <Scene captureRef={captureRef} painArea={tab==='pain'?painArea:null} sex={sex} visible={visible} selected={selected} opacity={opacity} rotate={rotate} view={view} reset={reset} zoom={zoom} onSelect={select} pin={tab==='pain'} adapted={adapted} painPoint={painPoint} painFocus={painFocus} marking={marking&&tab==='pain'} onMark={point=>{setPainPoint(point);setRegion(point.region);showPainAnatomy(point.region);setMarking(false);setResult(true);setToast('Pain location marked. You can save it with your conversation.');}}/>
 <AnimatePresence>{labels&&<motion.div key={selected} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} className="structure-label"><span style={{background:system[2]}}/><div><small>{tab==='pain'?'PAIN LOCATION / SELECTED':'SELECTED STRUCTURE'}</small><strong>{selectedPart.name}</strong></div><Crosshair size={16}/></motion.div>}</AnimatePresence>
 {tab==='pain'&&(marking||painPoint)&&<div className="marking-banner">{marking?'Click or tap the body surface to mark the painful spot.':painPoint?`Marked: ${painPoint.side} ${painPoint.region.toLowerCase()}`:''}{marking&&<button onClick={()=>setMarking(false)}>Cancel marking</button>}</div>}<div className="view-controls"><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(z+1,8))}><Plus size={18}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(z-1,-4))}><Minus size={18}/></button><i/><button aria-label="Reset view" onClick={()=>{setReset(r=>r+1);setZoom(0);setView('Front');}}><RotateCcw size={17}/></button><button aria-label="Toggle labels" className={labels?'control-active':''} onClick={()=>setLabels(v=>!v)}><Layers size={17}/></button><button aria-label="Full screen atlas" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else document.querySelector('.viewport')?.requestFullscreen?.().catch(()=>setToast('Full screen is unavailable.'));}}><Maximize2 size={17}/></button></div>
 <div className="orientation"><span>Y</span><div>↗ <b>Z</b> <span>→ X</span></div></div>
 <div className="viewport-bottom"><div className="camera-views">{['Front','Side','Back'].map(v=><button className={view===v?'active':''} key={v} onClick={()=>{setView(v);setReset(r=>r+1);}}>{v}</button>)}</div><button className={'rotate-button '+(rotate?'active':'')} onClick={()=>setRotate(r=>!r)}>{rotate?<Pause size={14}/>:<Play size={14}/>} Auto-rotate</button></div>
 <div className="canvas-caption"><Move size={13}/> Drag to rotate <span>·</span> Scroll to zoom <span>·</span> Click to discover</div><span className="schematic">{sex==='male'?'BODYPARTS3D · ADULT MALE REFERENCE':'HUMAN REFERENCE ATLAS · FEMALE REFERENCE'}</span>
 </section>
 <PanelResize side="right" width={widths.right} onResize={w=>resize('right',w)}/><aside className="right-panel"><Tabs value={tab} onValueChange={setTab}><TabsList className="detail-tabs"><TabsTrigger value="explore">Structure info</TabsTrigger><TabsTrigger value="pain"><Crosshair size={14}/> Pain explorer</TabsTrigger></TabsList></Tabs>
 <AnimatePresence mode="wait" initial={false}>{tab==='explore'?<motion.div key={'detail-'+selected} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:reduceMotion?0:.22}}><div className="detail-title"><span className="selection-index">ANATOMICAL STRUCTURE</span><span className="eyebrow" style={{color:system[2]}}>{system[1]} SYSTEM</span><h2>{selectedPart.name}</h2><span className="region-tag">{selectedPart.region}</span></div>{learning.scope&&<p className="learning-scope">{learning.scope}</p>}{[['What is this structure?',learning.what],['Why is it important?',learning.why],['What can happen if it is not working well?',learning.harm]].map(([heading,body])=><section className="learning-section" key={heading}><h3>{heading}</h3><p>{body}</p></section>)}<section className="learning-section"><h3>How can you care for it?</h3><div className="care-accordions">{learning.careSections.map(item=><details className="care-accordion" key={item.title}><summary>{item.title}<ChevronRight size={15} aria-hidden="true"/></summary><div className="care-content"><p>{item.body}</p>{item.steps&&<ol>{item.steps.map(step=><li key={step}>{step}</li>)}</ol>}<a href={item.source} target="_blank" rel="noreferrer">Read the guidance ↗</a></div></details>)}</div></section><a className="source-link" href={learning.source} target="_blank" rel="noreferrer">Health education source ↗</a><button className="pain-cta" onClick={()=>{setTab('pain');if(regions.includes(selectedPart.region))setRegion(selectedPart.region);}}><Crosshair size={19}/><span>Something doesn’t feel right?<small>Explore a pain location</small></span><ChevronRight size={16}/></button></motion.div>:
 <motion.div key="pain" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}}><div className="pain-heading"><span className="eyebrow">PAIN EXPLORER</span><h2>How are you feeling?</h2><p>Speak naturally, or type below.</p></div></motion.div>}</AnimatePresence>
 <div hidden={tab!=='pain'}><GuidedPain active={tab==='pain'} sex={sex} point={painPoint} onFocus={focusPain} onSuggest={area=>{focusPain(area);setMarking(false);showPainAnatomy(area);}} onRestorePoint={(point,preset)=>{if(preset)setSex(preset);setPainPoint(point);if(point){setRegion(point.region);setPainArea(point.region);setPainFocus({region:point.region,nonce:Date.now()});setVisible(['integumentary',...new Set((regionParts[point.region]||[]).map(id=>parts.find(p=>p.id===id)!.system))]);setOpacity(70);setRotate(false);setMarking(false);}}} onClear={()=>{setPainPoint(null);setPainArea(null);setMarking(false);}} capture={()=>{if(!captureRef.current)throw Error('Wait for the 3D model to finish loading.');return captureRef.current();}}/><details className="legacy-history"><summary>Earlier pain notes & conversations</summary><PainJournal restoreOnLoad={false} draft={painDraft} onRestore={restorePain} onFocus={focusPain} onClearPoint={()=>setPainPoint(null)}/></details></div></aside></div><footer><span><span className="footer-dot"/> <a href={assetUrl("/ATTRIBUTION.md")} target="_blank" rel="noreferrer">BodyParts3D / Human Reference Atlas · CC BY 4.0 ↗</a></span><span>{rawParts.length?rawParts.length.toLocaleString(): '…'} meshes · 13 systems <span className="footer-divider">|</span> PreDoc</span></footer>
 {info&&<div className="info-banner"><button aria-label="Close information" onClick={()=>setInfo(false)}><X size={17}/></button><strong>An atlas for learning.</strong><p>Real segmented geometry from BodyParts3D (adult male) and Human Reference Atlas (female). These are educational reference datasets, not a patient scan or a complete clinical atlas. Female coverage is partial. Optional adapted additions fill skeletal gaps using fitted male-derived bone geometry and lower-limb gaps using muscles from a separate female donor. These are clearly labeled, not verified female anatomy. Pregnancy structures are excluded; upper-body muscle coverage remains incomplete. Pain highlights show related anatomy, not a diagnosis.</p><a href={assetUrl("/ATTRIBUTION.md")} target="_blank" rel="noreferrer">Model sources, scope & attribution ↗</a><a className="source-link" href={assetUrl("/RESOURCE_VALIDATION.md")} target="_blank" rel="noreferrer">Resource validation report ↗</a></div>}
 {shareOpen&&<div className="share-popover"><button className="close-share" onClick={()=>setShareOpen(false)} aria-label="Close sharing"><X size={16}/></button><h3>Share this view</h3><p>{tab==='pain'?'The link includes your body preset, selected structure, pain region, type and intensity. Only share it with someone you trust. Notes are excluded.':'The link includes your body preset and selected structure.'}</p><input aria-label="Share link" readOnly value={shareURL} onFocus={e=>e.target.select()}/><button className="primary-button" onClick={share}><Share2 size={15}/> Copy link</button></div>}<AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}} className="toast" role="status"><Check size={16}/>{toast}</motion.div>}</AnimatePresence>
 </main></MotionConfig>;
}
