'use client';
import {useState,useEffect} from 'react';
import {AnimatePresence,motion,MotionConfig,useReducedMotion} from 'framer-motion';
import dynamic from 'next/dynamic';
import {Activity,ArrowUpRight, Bone,Brain, Check, ChevronRight, CircleHelp, Crosshair, Eye, Heart, Layers, Maximize2, Minus, Move, Pause, Play, Plus, RotateCcw, Search, Share2, ShieldCheck, Sparkles, X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {parts,systems,System,anatomySource,Part} from './atlas/data';
import {loadAtlas,describeMesh,category,MeshPart} from './atlas/model';
const Scene=dynamic(()=>import('./atlas/Scene'),{ssr:false,loading:()=> <div className="model-loading">Preparing your atlas…</div>});
const initial:System[]=['skeletal','muscular','cardiovascular','nervous'];
const regions=['Head','Neck','Shoulder','Chest','Back','Abdomen','Pelvis','Arm','Hand','Leg','Knee','Foot'];
const regionParts:Record<string,string[]>={Head:['brain','eyes','skull'],Neck:['nerves','thyroid','spine'],Shoulder:['deltoid','clavicle','nerves'],Chest:['heart','lungs','ribs','pectoral'],Back:['spine','backmuscle','nerves','kidneys'],Abdomen:['stomach','intestines','liver','kidneys'],Pelvis:['bladder','pelvis'],Arm:['biceps','humerus','nerves'],Hand:['hand','nerves'],Leg:['quadriceps','femur','nerves','veins'],Knee:['patella','femur','quadriceps'],Foot:['foot','nerves']};
export default function Home(){
 const reduceMotion=useReducedMotion();
 const [sex,setSex]=useState('male'),[visible,setVisible]=useState<System[]>(initial),[selected,setSelected]=useState('pectoral'),[query,setQuery]=useState(''),[tab,setTab]=useState('explore'),[opacity,setOpacity]=useState(100),[rotate,setRotate]=useState(false),[view,setView]=useState('Front'),[reset,setReset]=useState(0),[zoom,setZoom]=useState(0),[labels,setLabels]=useState(true),[region,setRegion]=useState('Chest'),[quality,setQuality]=useState('Aching'),[severity,setSeverity]=useState(4),[duration,setDuration]=useState('Today'),[notes,setNotes]=useState(''),[result,setResult]=useState(false),[urgent,setUrgent]=useState(false),[toast,setToast]=useState(''),[info,setInfo]=useState(false),[shareOpen,setShareOpen]=useState(false);
 const [realParts,setRealParts]=useState<Part[]>([]),[rawParts,setRawParts]=useState<MeshPart[]>([]),[supplement,setSupplement]=useState(false);
 const allParts=[...parts,...realParts];
 const selectedPart=allParts.find(p=>p.id===selected)||parts[0],system=systems.find(s=>s[0]===selectedPart.system)!;
 useEffect(()=>{let active=true;loadAtlas(sex).then(data=>{if(active){setRawParts(data.parts);setRealParts(data.parts.map(p=>describeMesh(p,sex)));}}).catch(()=>setToast('The anatomy catalog could not load. Reload to retry.'));return()=>{active=false;};},[sex]);
 const eligible=parts.filter(p=>(!p.sex||p.sex===sex)&&(!rawParts.length||rawParts.some(m=>category(m)===p.id))),matches=[...eligible,...realParts].filter(p=>(!p.sex||p.sex===sex)).filter(p=>(p.name+' '+p.system+' '+p.region).toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{
 const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!context?.registerTool)return;
 const lifecycle=new AbortController();
 try{Promise.resolve(context.registerTool({name:'configure_anatomy_view',description:'Select a male or female anatomy preset and focus a named structure in the visible atlas.',inputSchema:{type:'object',properties:{sex:{type:'string',enum:['male','female']},structureId:{type:'string',enum:parts.map(p=>p.id)}},required:['sex','structureId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const args=input as {sex:string;structureId:string};const part=parts.find(p=>p.id===args?.structureId);if(!part||!['male','female'].includes(args.sex)||(part.sex&&part.sex!==args.sex))throw new Error('Choose a valid structure for this anatomy preset.');setSex(args.sex);setSelected(part.id);setVisible([part.system]);setTab('explore');await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {sex:args.sex,selected:part.id,visibleSystems:[part.system]};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{try{const data=JSON.parse(decodeURIComponent(location.hash.slice(1)));if(data.sex==='female'||data.sex==='male')setSex(data.sex);if(parts.some(p=>p.id===data.part)){setSelected(data.part);setVisible([parts.find(p=>p.id===data.part)!.system]);}else if(typeof data.part==='string'){loadAtlas(data.sex==='female'?'female':'male').then(atlas=>{const p=atlas.parts.find(p=>p.id===data.part);if(p){const desc=describeMesh(p,data.sex);setSelected(desc.id);setVisible([desc.system]);}}).catch(()=>{});}if(regions.includes(data.region)){setRegion(data.region);setTab('pain');if(['Aching','Sharp','Burning','Tingling','Throbbing','Cramping'].includes(data.quality))setQuality(data.quality);if(Number.isInteger(data.severity)&&data.severity>=1&&data.severity<=10)setSeverity(data.severity);}}catch{}},[]);
 function select(id:string){const p=allParts.find(p=>p.id===id);if(!p)return;setSelected(id);setVisible(v=>v.includes(p.system)?v:[...v,p.system]);if(tab==='pain'){if(regions.includes(p.region))setRegion(p.region);setResult(false);}}
 function changeSex(value:string){setSex(value);setRawParts([]);setRealParts([]);setSupplement(false);setSelected(value==='female'?'uterus':'pectoral');setVisible(value==='female'?['integumentary','respiratory','digestive','reproductive','cardiovascular']:initial);setResult(false);}
 function toggle(id:System){setVisible(v=>v.includes(id)?v.filter(s=>s!==id):[...v,id]);}
 function analyze(){let ids=regionParts[region]||['nerves'];if(quality==='Tingling'||quality==='Burning')ids=[...new Set([...ids,'nerves'])];if(region==='Pelvis')ids=[...ids,...(sex==='female'?['uterus','ovaries']:['prostate','testes'])];setVisible([...new Set(ids.map(id=>parts.find(p=>p.id===id)!.system))]);setSelected(ids[0]);setResult(true);}
 async function share(){const data=tab==='pain'?{sex,part:selected,region,quality,severity}:{sex,part:selected};const url=location.origin+location.pathname+'#'+encodeURIComponent(JSON.stringify(data));try{await navigator.clipboard.writeText(url);setToast('Link copied. Notes and emergency answers are excluded.');setShareOpen(false);}catch{setToast('Clipboard unavailable. Use the link field to copy manually.');}return url;}
 const shareURL=typeof window==='undefined'?'':window.location.origin+window.location.pathname+'#'+encodeURIComponent(JSON.stringify(tab==='pain'?{sex,part:selected,region,quality,severity}:{sex,part:selected}));
 return <MotionConfig reducedMotion="user" transition={{duration:.28,ease:[.22,1,.36,1]}}><main className="atlas-app">
 <header className="topbar"><a className="brand" href="/" aria-label="Human Atlas home"><span className="brandmark"><Activity size={24}/></span><span>human<span className="brand-light">atlas</span><small>ANATOMY STUDIO</small></span></a><nav><button className={tab==='explore'?'nav-active':''} onClick={()=>setTab('explore')}>Anatomy explorer</button><button className={tab==='pain'?'nav-active':''} onClick={()=>setTab('pain')}>Pain explorer <span className="new">BETA</span></button></nav><div className="top-actions"><button className="icon-button" aria-label="About this atlas" onClick={()=>setInfo(v=>!v)}><CircleHelp size={19}/></button><button className="share-button" onClick={()=>setShareOpen(true)}><Share2 size={15}/> Share view</button></div></header>
 <div className="workspace">
 <motion.aside initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} className="left-panel"><div className="panel-top"><span className="eyebrow">HUMAN ATLAS / 01</span><h1>Layers of life<span>.</span></h1><p>Real anatomy. A deeper perspective.</p></div>
 <Tabs value={sex} onValueChange={changeSex}><TabsList className="sex-tabs"><TabsTrigger value="male">♂ &nbsp; Male</TabsTrigger><TabsTrigger value="female">♀ &nbsp; Female</TabsTrigger></TabsList></Tabs>
 <label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a structure…" aria-label="Search anatomy"/><span>⌕</span></label>
 <div className="section-heading"><h2>{query?'SEARCH RESULTS':'BODY SYSTEMS'}</h2><button onClick={()=>setVisible(visible.length===systems.length?[]:systems.map(s=>s[0]))}>{visible.length===systems.length?'Hide all':'Show all'}</button></div>
 <div className="systems-list">{query?<div className="search-results">{matches.length?matches.slice(0,120).map(p=><button key={p.id} onClick={()=>select(p.id)}><span>{p.name}<small>{p.region} · {p.system}</small></span><ChevronRight size={15}/></button>):<p>No structures match “{query}”. Try a body region or system.</p>}</div>:systems.map(([id,name,color,desc])=><motion.div layout className={'system-row '+(visible.includes(id)?'is-visible':'')} key={id}><button className="system-main" disabled={rawParts.length>0&&!realParts.some(p=>p.system===id)} onClick={()=>{setVisible([id]);setSelected(eligible.find(p=>p.system===id)?.id||realParts.find(p=>p.system===id)?.id||'skin');}} title={'Focus on '+name}><span className="system-icon" style={{color}}>{id==='skeletal'?<Bone size={19}/>:id==='nervous'?<Brain size={19}/>:id==='cardiovascular'?<Heart size={19}/>:id==='sensory'?<Eye size={19}/>:<Activity size={19}/>}</span><span>{name}<small>{desc}</small>{rawParts.length>0&&!realParts.some(p=>p.system===id)&&<em>Not in this reference</em>}</span></button><Switch disabled={rawParts.length>0&&!realParts.some(p=>p.system===id)} checked={visible.includes(id)} onCheckedChange={()=>toggle(id)} aria-label={'Show '+name} size="sm"/></motion.div>)}</div>
 <div className="left-bottom">{sex==='female'&&<div className="supplement-toggle"><div><strong>Supplemental anatomy</strong><p>Male-derived bones & separate female leg muscles</p></div><Switch checked={supplement} onCheckedChange={setSupplement} aria-label="Show supplemental female anatomy"/></div>}<div className="section-heading"><h2>LAYER OPACITY</h2><span>{opacity}%</span></div><Slider aria-label="Layer opacity" min={15} max={100} value={[opacity]} onValueChange={v=>setOpacity(v[0])}/><div className="subtle-label"><span>Transparent</span><span>Solid</span></div><div className="education-note"><ShieldCheck size={17}/><span>Reference anatomy<br/>For education, not diagnosis.</span></div></div>
 </motion.aside>
 <section className="viewport"><div className="viewport-heading"><div><span className="eyebrow">ANATOMY EXPLORER</span><h2>{sex==='male'?'Male':'Female'} anatomy <span>/ {visible.length===1?systems.find(s=>s[0]===visible[0])?.[1]:'Full body'}</span></h2></div><span className="model-badge"><span/> LIVE 3D</span></div>
 <Scene sex={sex} visible={visible} selected={selected} opacity={opacity} rotate={rotate} view={view} reset={reset} zoom={zoom} onSelect={select} pin={tab==='pain'} supplement={supplement}/>
 <AnimatePresence>{labels&&<motion.div key={selected} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} className="structure-label"><span style={{background:system[2]}}/><div><small>{tab==='pain'?'PAIN LOCATION / SELECTED':'SELECTED STRUCTURE'}</small><strong>{selectedPart.name}</strong></div><Crosshair size={16}/></motion.div>}</AnimatePresence>
 <div className="view-controls"><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(z+1,8))}><Plus size={18}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(z-1,-4))}><Minus size={18}/></button><i/><button aria-label="Reset view" onClick={()=>{setReset(r=>r+1);setZoom(0);setView('Front');}}><RotateCcw size={17}/></button><button aria-label="Toggle labels" className={labels?'control-active':''} onClick={()=>setLabels(v=>!v)}><Layers size={17}/></button><button aria-label="Full screen atlas" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else document.querySelector('.viewport')?.requestFullscreen?.().catch(()=>setToast('Full screen is unavailable.'));}}><Maximize2 size={17}/></button></div>
 <div className="orientation"><span>Y</span><div>↗ <b>Z</b> <span>→ X</span></div></div>
 <div className="viewport-bottom"><div className="camera-views">{['Front','Side','Back'].map(v=><button className={view===v?'active':''} key={v} onClick={()=>{setView(v);setReset(r=>r+1);}}>{v}</button>)}</div><button className={'rotate-button '+(rotate?'active':'')} onClick={()=>setRotate(r=>!r)}>{rotate?<Pause size={14}/>:<Play size={14}/>} Auto-rotate</button></div>
 <div className="canvas-caption"><Move size={13}/> Drag to rotate <span>·</span> Scroll to zoom <span>·</span> Click to discover</div><span className="schematic">{sex==='male'?'BODYPARTS3D · ADULT MALE REFERENCE':'HUMAN REFERENCE ATLAS · FEMALE REFERENCE'}</span>
 </section>
 <aside className="right-panel"><Tabs value={tab} onValueChange={setTab}><TabsList className="detail-tabs"><TabsTrigger value="explore">Structure info</TabsTrigger><TabsTrigger value="pain"><Crosshair size={14}/> Pain explorer</TabsTrigger></TabsList></Tabs>
 <AnimatePresence mode="wait" initial={false}>{tab==='explore'?<motion.div key={'detail-'+selected} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:reduceMotion?0:.22}}><div className="detail-title"><span className="selection-index">ANATOMICAL STRUCTURE</span><div className="organ-icon" style={{color:system[2],background:system[2]+'18'}}>{selectedPart.system==='skeletal'?<Bone size={32}/>:selectedPart.system==='nervous'?<Brain size={32}/>:<Heart size={32}/>}</div><span className="eyebrow" style={{color:system[2]}}>{system[1]} SYSTEM</span><h2>{selectedPart.name}</h2><span className="region-tag">{selectedPart.region}</span></div><p className="description">{selectedPart.description}</p>{realParts.some(p=>p.id===selected)&&<div className="mesh-reference"><span>SEGMENTED MESH</span><code>{rawParts.find(p=>p.id===selected)?.conceptId}</code></div>}<div className="detail-block"><h3><Activity size={16}/> {realParts.some(p=>p.id===selected)?'Related anatomy & function':'What it does'}</h3><p>{selectedPart.function}</p></div><div className="fact-box"><Sparkles size={17}/><div><h3>A little more to know</h3><p>{selectedPart.fact}</p></div></div><button className="primary-button" onClick={()=>setVisible([selectedPart.system])}><Crosshair size={16}/> Isolate this system <ArrowUpRight size={16}/></button><div className="detail-block structures"><h3>Explore this system <span>{eligible.filter(p=>p.system===selectedPart.system).length}</span></h3>{eligible.filter(p=>p.system===selectedPart.system).map(p=><button className={selected===p.id?'selected':''} key={p.id} onClick={()=>select(p.id)}>{p.name}<ChevronRight size={14}/></button>)}</div><a className="source-link" href={anatomySource} target="_blank" rel="noreferrer">Learning reference · OpenStax <ArrowUpRight size={13}/></a><button className="pain-cta" onClick={()=>{setTab('pain');if(regions.includes(selectedPart.region))setRegion(selectedPart.region);}}><Crosshair size={19}/><span>Something doesn’t feel right?<small>Explore a pain location</small></span><ChevronRight size={16}/></button></motion.div>:
 <motion.div key="pain" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} className="pain-panel"><div className="pain-heading"><span className="eyebrow">LISTEN TO YOUR BODY</span><h2>Where does it hurt?</h2><p>Select a structure on the body or choose a region below.</p></div><label className="field-label">Body region</label><Select value={region} onValueChange={v=>{setRegion(v);setResult(false);select(regionParts[v][0]);setRegion(v);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{regions.map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select><label className="field-label">What does it feel like?</label><div className="pain-types">{['Aching','Sharp','Burning','Tingling','Throbbing','Cramping'].map(q=><button className={quality===q?'active':''} key={q} onClick={()=>{setQuality(q);setResult(false);}}>{q}</button>)}</div><label className="field-label">Pain intensity <strong>{severity} / 10</strong></label><Slider min={1} max={10} step={1} value={[severity]} onValueChange={v=>{setSeverity(v[0]);setResult(false);}} aria-label="Pain intensity"/><div className="subtle-label"><span>Mild</span><span>Severe</span></div><label className="field-label">When did it start?</label><Select value={duration} onValueChange={v=>{setDuration(v);setResult(false);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Today','1–3 days ago','Over a week ago','Recurring'].map(d=><SelectItem key={d} value={d}>{d}</SelectItem>)}</SelectContent></Select><label className="field-label" htmlFor="notes">Anything else? <span>Optional</span></label><textarea id="notes" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What brings it on? Does it spread?" maxLength={2000}/><div className="urgent-check"><Switch id="urgent" checked={urgent} onCheckedChange={v=>{setUrgent(v);setResult(false);}}/><label htmlFor="urgent">Sudden severe pain, difficulty breathing, fainting, or new weakness / speech trouble</label></div>{urgent&&<div className="emergency" role="alert"><strong>Seek emergency care now.</strong><p>Call your local emergency number. Do not wait for this explorer or drive yourself if seriously unwell.</p></div>}<button className="primary-button" onClick={analyze}><Crosshair size={16}/> Explore related anatomy <ArrowUpRight size={16}/></button>
 {result&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} className="pain-result" aria-live="polite"><h3>{urgent?'Emergency symptoms reported':'Structures to learn about'}</h3><p>{region} · {quality.toLowerCase()} · {severity}/10 · {duration.toLowerCase()}</p>{(regionParts[region]||[]).map(id=><button onClick={()=>select(id)} key={id}>{parts.find(p=>p.id===id)?.name}<ArrowUpRight size={13}/></button>)}<p>{quality==='Tingling'?'Tingling can occur with irritation or compression of nerves, among other causes.':quality==='Burning'?'Burning sensations can involve skin or nerves; in the chest or upper abdomen, reflux is one possible cause.':'Pain in this region can arise from muscles, joints, organs, nerves, or a different location through referred pain.'} Location and sensation alone cannot determine the cause.</p><p className="care-guidance">{urgent?'Get emergency help now.':severity>=8?'Severe pain needs urgent medical assessment.':region==='Chest'?'Get medical advice for chest pain. Persistent pressure, spreading pain, sweating or breathlessness requires emergency help.':duration!=='Today'?'Arrange a clinical assessment for persistent or recurring pain, or sooner if it worsens.':'Seek medical advice for unexplained, worsening or persistent pain.'}</p><button className="download" onClick={()=>{const report=`Human Atlas — symptom notes (not a diagnosis)\nRegion: ${region}\nSensation: ${quality}\nIntensity: ${severity}/10\nOnset: ${duration}\nEmergency symptoms reported: ${urgent?'Yes':'No'}\nNotes: ${notes}\n\nAnatomy highlights are educational and do not identify the cause.`;const u=URL.createObjectURL(new Blob([report],{type:'text/plain'}));const a=document.createElement('a');a.href=u;a.download='human-atlas-symptom-notes.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}}>Download my symptom notes ↓</button></motion.div>}
 <p className="privacy-note">Your notes stay in this page and clear when you reload. This explorer does not diagnose conditions or rule out emergencies.</p><div className="source-links"><a href="https://www.nhs.uk/symptoms/chest-pain/" target="_blank" rel="noreferrer">NHS · Chest pain ↗</a><a href="https://www.nhs.uk/symptoms/stomach-ache/" target="_blank" rel="noreferrer">NHS · Abdominal pain ↗</a></div></motion.div>}</AnimatePresence>
 </aside></div><footer><span><span className="footer-dot"/> <a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">BodyParts3D / Human Reference Atlas · CC BY 4.0 ↗</a></span><span>{rawParts.length?rawParts.length.toLocaleString(): '…'} meshes · 13 systems <span className="footer-divider">|</span> Human Atlas / 01</span></footer>
 {info&&<div className="info-banner"><button aria-label="Close information" onClick={()=>setInfo(false)}><X size={17}/></button><strong>An atlas for learning.</strong><p>Real segmented geometry from BodyParts3D (adult male) and Human Reference Atlas (female). These are educational reference datasets, not a patient scan or a complete clinical atlas. Female coverage is partial. Optional supplementary bones are male-derived; supplemental leg muscles come from a separate female donor. Pain highlights show related anatomy, not a diagnosis.</p><a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">Model sources, scope & attribution ↗</a></div>}
 {shareOpen&&<div className="share-popover"><button className="close-share" onClick={()=>setShareOpen(false)} aria-label="Close sharing"><X size={16}/></button><h3>Share this view</h3><p>{tab==='pain'?'The link includes your body preset, selected structure, pain region, type and intensity. Only share it with someone you trust. Notes are excluded.':'The link includes your body preset and selected structure.'}</p><input aria-label="Share link" readOnly value={shareURL} onFocus={e=>e.target.select()}/><button className="primary-button" onClick={share}><Share2 size={15}/> Copy link</button></div>}<AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}} className="toast" role="status"><Check size={16}/>{toast}</motion.div>}</AnimatePresence>
 </main></MotionConfig>;
}
