export const systems = [
 ['skeletal','Skeletal','#d7c5a6','Bones, joints & support'],['muscular','Muscular','#b96752','Movement & posture'],['cardiovascular','Heart & arteries','#d85555','Heart & arterial circulation'],['venous','Veins','#668bd1','Venous return'],['nervous','Nervous','#dfb54c','Brain, spinal cord & nerves'],['respiratory','Respiratory','#c68991','Breathing & gas exchange'],['digestive','Digestive','#c58d65','Digestion & absorption'],['sensory','Sensory organs','#68b8bb','Sight, hearing, taste & smell'],['urinary','Urinary','#a988b8','Fluid balance & waste'],['endocrine','Endocrine','#dca563','Hormones & regulation'],['lymphatic','Lymphatic','#85ae83','Immunity & fluid return'],['reproductive','Reproductive','#c88baf','Sex-specific reproductive anatomy'],['integumentary','Integumentary','#c6b09a','Skin & protection']
] as const;
export type System = typeof systems[number][0];
export type Part = {id:string;name:string;system:System;region:string;description:string;function:string;fact:string; sex?:string};
const rows: [string,string,System,string,string,string,string,string?][] = [
 ['skull','Skull','skeletal','Head','The bony framework of the head surrounds the brain and forms the face.','Protects the brain and supports the sensory structures.','The adult skull consists of cranial and facial bones.'],
 ['spine','Vertebral column','skeletal','Back','A segmented column extending from the skull to the pelvis.','Protects the spinal cord and supports an upright posture.','Intervertebral discs cushion most adjacent vertebrae.'],
 ['ribs','Rib cage','skeletal','Chest','Curved ribs connect with the thoracic spine; most attach to the sternum directly or indirectly.','Protects the heart and lungs while moving during breathing.','Most people have 12 pairs of ribs.'],
 ['clavicle','Clavicle','skeletal','Shoulder','The collarbone links the breastbone and shoulder blade.','Positions the shoulder and transfers forces to the trunk.','It is one of the most commonly fractured bones.'],
 ['pelvis','Pelvis','skeletal','Pelvis','A ring formed by the hip bones, sacrum and coccyx.','Transfers body weight to the legs and protects pelvic organs.','Pelvic shape varies between individuals and on average by sex.'],
 ['humerus','Humerus','skeletal','Arm','The long bone between the shoulder and elbow.','Provides a lever for upper-arm movement.','Its head articulates with the shoulder blade.'],
 ['forearm','Radius & ulna','skeletal','Arm','The two long bones of the forearm.','Support wrist and elbow movement and forearm rotation.','The radius is on the thumb side in anatomical position.'],
 ['hand','Hand bones','skeletal','Hand','Carpals, metacarpals and phalanges form the wrist and hand.','Enable precise grasping and manipulation.','Each hand normally contains 27 bones.'],
 ['femur','Femur','skeletal','Leg','The thigh bone extends from the hip to the knee.','Bears weight and acts as a lever during walking.','It is the longest bone in the body.'],
 ['patella','Patella','skeletal','Knee','A sesamoid bone within the quadriceps tendon.','Improves the leverage of the knee-extending muscles.','It is commonly called the kneecap.'],
 ['lowerleg','Tibia & fibula','skeletal','Leg','Two bones connect the knee region to the ankle.','The tibia bears most weight; the fibula supports ankle stability.','The fibula lies on the outer side of the leg.'],
 ['foot','Foot bones','skeletal','Foot','Tarsals, metatarsals and phalanges form the foot.','Support the arches and propel the body during walking.','Each foot normally contains 26 bones.'],
 ['pectoral','Pectoralis major','muscular','Chest','A broad muscle across the front of the upper chest.','Moves the arm inward and helps rotate it.','Its fibers attach to the humerus.'],['deltoid','Deltoid','muscular','Shoulder','A rounded muscle covering the shoulder.','Raises the arm and contributes to rotation.','Its different portions move the arm in different directions.'],['biceps','Biceps brachii','muscular','Arm','A two-headed muscle on the front of the upper arm.','Flexes the elbow and turns the palm upward.','It crosses both the shoulder and elbow.'],['abdominal','Abdominal muscles','muscular','Abdomen','Layers of muscle form the abdominal wall.','Stabilize the trunk and compress abdominal contents.','These muscles also assist forced expiration.'],['quadriceps','Quadriceps','muscular','Leg','A group of four muscles on the front of the thigh.','Straightens the knee.','Its tendon connects to the patella.'],['calf','Calf muscles','muscular','Leg','Gastrocnemius and soleus form much of the posterior calf.','Point the foot downward during standing and walking.','They connect to the heel through the Achilles tendon.'],['backmuscle','Back muscles','muscular','Back','Muscles beside the spine and across the back.','Maintain posture and move the spine and shoulders.','Deep and superficial layers have different roles.'],
 ['heart','Heart','cardiovascular','Chest','A muscular, four-chambered organ between the lungs, slightly left of the midline.','Pumps blood through the lungs and the rest of the body.','Valves keep blood flowing in one direction.'],['arteries','Major arteries','cardiovascular','Whole body','Arteries carry blood away from the heart through branching vessels.','Deliver blood to tissues and to the lungs.','Pulmonary arteries carry oxygen-poor blood.'],['veins','Major veins','venous','Whole body','Veins return blood toward the heart.','Return blood from tissues and act as a blood reservoir.','Many limb veins have valves that help prevent backflow.'],
 ['brain','Brain','nervous','Head','The central organ of the nervous system within the skull.','Integrates sensation, movement, thought and vital regulation.','The cerebrum, cerebellum and brainstem have distinct roles.'],['cord','Spinal cord','nervous','Back','Nervous tissue running within the vertebral canal.','Carries signals between the brain and body and coordinates reflexes.','It ends above the bottom of the vertebral column.'],['nerves','Peripheral nerves','nervous','Whole body','Branching nerves outside the brain and spinal cord.','Transmit sensory and motor information.','Some fibers regulate involuntary organ activity.'],
 ['lungs','Lungs','respiratory','Chest','Paired organs in the thorax containing branching airways and air sacs.','Exchange oxygen and carbon dioxide with the blood.','The right lung has three lobes; the left has two.'],['trachea','Trachea & bronchi','respiratory','Chest','The windpipe branches into the main airways of the lungs.','Conduct air and help remove inhaled particles.','Cartilage helps keep the larger airways open.'],['diaphragm','Diaphragm','respiratory','Chest','A dome-shaped muscle separating the chest and abdomen.','Its contraction expands the chest during inspiration.','It is the principal muscle of quiet breathing.'],
 ['liver','Liver','digestive','Abdomen','A large organ mainly in the right upper abdomen.','Processes nutrients, makes bile and metabolizes substances.','The gallbladder stores bile produced by the liver.'],['stomach','Stomach','digestive','Abdomen','A muscular sac in the upper left abdomen.','Mixes food with acid and enzymes to begin protein digestion.','It releases its contents gradually into the small intestine.'],['intestines','Small & large intestines','digestive','Abdomen','A folded digestive tube extending from the stomach to the rectum.','Absorbs nutrients and water and forms stool.','Most nutrient absorption occurs in the small intestine.'],['esophagus','Esophagus','digestive','Chest','A muscular tube connecting the throat and stomach.','Moves swallowed food by coordinated contractions.','It passes through the diaphragm.'],['pancreas','Pancreas','endocrine','Abdomen','A gland behind the stomach with digestive and hormonal roles.','Produces digestive enzymes and hormones including insulin.','Its endocrine cells are grouped in pancreatic islets.'],
 ['eyes','Eyes','sensory','Head','Paired visual organs located in the bony orbits.','Focus light onto the retina, where photoreceptors detect it.','The optic nerve carries visual information to the brain.'],['ears','Ears','sensory','Head','Outer, middle and inner ear structures.','Enable hearing and contribute to balance.','The cochlea detects sound; vestibular structures detect motion.'],['nose','Nose','sensory','Head','Nasal passages contain receptors for smell.','Filters and conditions air and senses odors.','Smell contributes strongly to flavor perception.'],['tongue','Tongue','sensory','Head','A muscular organ within the mouth.','Supports taste, swallowing and speech.','Taste buds contain specialized receptor cells.'],
 ['kidneys','Kidneys','urinary','Abdomen','Paired organs toward the back of the abdomen.','Filter blood and regulate water, electrolytes and acid–base balance.','Urine flows to the bladder through the ureters.'],['bladder','Urinary bladder','urinary','Pelvis','A hollow muscular organ in the pelvis.','Stores urine before it leaves through the urethra.','Its wall stretches as it fills.'],['thyroid','Thyroid gland','endocrine','Neck','A butterfly-shaped gland at the front of the neck.','Produces hormones that regulate metabolism.','Iodine is required to make thyroid hormones.'],['adrenals','Adrenal glands','endocrine','Abdomen','Small glands above the kidneys.','Produce hormones involved in stress responses and salt balance.','Their cortex and medulla produce different hormones.'],['pituitary','Pituitary gland','endocrine','Head','A small gland beneath the brain.','Regulates growth, reproduction and other endocrine glands.','It is closely connected to the hypothalamus.'],
 ['lymph','Lymph nodes & vessels','lymphatic','Whole body','A network that drains tissue fluid through lymph nodes.','Returns fluid to circulation and supports immune surveillance.','Lymph nodes contain immune cells.'],['spleen','Spleen','lymphatic','Abdomen','An organ in the upper left abdomen near the stomach.','Filters blood and supports immune responses.','It removes aging red blood cells.'],['thymus','Thymus','lymphatic','Chest','An immune organ behind the sternum.','Supports maturation of T lymphocytes.','It is relatively larger in children.'],
 ['uterus','Uterus & uterine tubes','reproductive','Pelvis','A muscular pelvic organ connected to paired uterine tubes.','Supports pregnancy; tubes transport oocytes toward the uterus.','The endometrium changes during the menstrual cycle.','female'],['ovaries','Ovaries','reproductive','Pelvis','Paired gonads near the uterus.','Produce oocytes and hormones including estrogen and progesterone.','Ovarian activity changes through the reproductive lifespan.','female'],['testes','Testes','reproductive','Pelvis','Paired gonads located in the scrotum.','Produce sperm and testosterone.','Sperm mature further in the epididymis.','male'],['prostate','Prostate gland','reproductive','Pelvis','A gland below the bladder surrounding part of the urethra.','Contributes fluid to semen.','Its size can change with age.','male'],['skin','Skin','integumentary','Whole body','The external tissue covering the body.','Provides a barrier, sensation and temperature regulation.','The epidermis and dermis are its main layers.']
];
export const parts:Part[]=rows.map(([id,name,system,region,description,fn,fact,sex])=>({id,name,system,region,description,function:fn,fact,sex}));
export const anatomySource='https://openstax.org/books/anatomy-and-physiology-2e/pages/1-2-structural-organization-of-the-human-body';
