import {careSections} from './care';
import {Part,System,parts} from './data';
import {MeshPart,category} from './model';
const descriptions:Record<string,[string,string]>={
 skull:['The hard bones around your brain and face.','They shield your brain and support your face, jaw and teeth.'],spine:['The stack of small back bones, with cushions between most of them.','It holds you upright, lets you bend and protects the main nerve pathway in your back.'],ribs:['The curved bones around your chest.','They protect your heart and lungs while allowing your chest to move as you breathe.'],clavicle:['Your collarbone, linking the breastbone to the shoulder.','It helps hold your shoulder in position so your arm can move.'],pelvis:['The strong ring of bones at the base of your back.','It carries weight between your spine and legs and protects organs in your lower belly.'],humerus:['The long bone inside your upper arm.','It helps your shoulder and elbow move so you can reach and lift.'],forearm:['The two bones between your elbow and wrist.','They support your forearm and let you turn your palm up and down.'],hand:['The small bones in your wrist, palm and fingers.','They give your hand both strength and flexibility for gripping and precise tasks.'],femur:['Your thigh bone, between your hip and knee.','It carries much of your body weight when you stand, walk or run.'],patella:['Your kneecap, at the front of your knee.','It protects the front of the knee and helps the thigh muscles straighten your leg.'],lowerleg:['The two bones between your knee and ankle.','They support standing and help keep your ankle steady.'],foot:['The small bones making up your heel, arches and toes.','They spread your weight and help you balance and push off the ground.'],
 pectoral:['A large chest muscle attached to your upper arm.','It helps you push, hug and bring your arm across your body.'],deltoid:['The muscle that makes the rounded shape of your shoulder.','It helps raise and position your arm.'],biceps:['A muscle on the front of your upper arm.','It helps bend your elbow and turn your palm upward.'],abdominal:['Layers of muscle across the front and sides of your belly.','They support your trunk and work with your back muscles during movement.'],quadriceps:['Four large muscles on the front of your thigh.','They straighten your knee when you stand up, climb stairs or kick.'],calf:['The muscles behind your lower leg.','They help you rise onto your toes and push forward when walking.'],backmuscle:['Layers of muscle beside your spine and across your back.','They help hold your posture and move your trunk and shoulders.'],
 heart:['A muscular pump in your chest.','It keeps blood moving so your body receives oxygen and nutrients.'],arteries:['Blood vessels that carry blood away from your heart.','They deliver blood to your organs and to your lungs.'],veins:['Blood vessels that return blood toward your heart.','They complete the circulation loop so blood can keep moving through your body.'],brain:['The body’s main control center inside your skull.','It helps you think, remember, move and make sense of what you feel.'],cord:['A bundle of nerve tissue running inside your backbone.','It carries messages between your brain and body and controls some quick reflexes.'],nerves:['The body’s message-carrying cables outside the brain and spinal cord.','They help you feel touch and temperature, move muscles and control organs.'],
 lungs:['The two breathing organs in your chest.','They bring oxygen into your blood and remove carbon dioxide when you breathe out.'],trachea:['Your windpipe and the larger tubes that carry air into your lungs.','They provide an open route for air and help clear particles from it.'],diaphragm:['A broad breathing muscle below your lungs.','It moves downward to help draw air into your chest.'],liver:['A large organ under the ribs on the right side of your belly.','It processes nutrients, makes fluid that helps digest fats and handles many substances in blood.'],stomach:['A stretchy pouch between your food pipe and intestine.','It stores and mixes food before passing it along for digestion.'],intestines:['The long, folded tubes that carry food through your belly.','They absorb nutrients and water, then move waste toward the outside.'],esophagus:['The food pipe from your throat to your stomach.','Its muscles move swallowed food and drink downward.'],pancreas:['An organ behind your stomach.','It makes digestive juices and hormones that help control blood sugar.'],
 eyes:['The organs that detect light at the front of your head.','They help you see shapes, colors and movement.'],ears:['The hearing and balance structures on and inside your head.','They turn sound into nerve messages and help your brain track your balance.'],nose:['The air passages and smell-sensing area behind your nostrils.','They help filter incoming air and let you recognize smells.'],tongue:['The flexible muscle inside your mouth.','It helps you taste, speak, move food and swallow.'],kidneys:['Two organs toward the back of your belly.','They filter waste from blood and help balance fluid and salts.'],bladder:['A stretchy storage pouch low in your belly.','It holds urine until you are ready to pass it.'],thyroid:['A small gland at the front of your neck.','Its hormones help set the pace at which your body uses energy.'],adrenals:['Small hormone-making glands above your kidneys.','They help manage stress responses, blood pressure and salt balance.'],pituitary:['A pea-sized hormone-making gland beneath your brain.','It sends signals involved in growth and the work of several other glands.'],lymph:['A network of small vessels and filtering stations called lymph nodes.','It returns extra tissue fluid to the blood and supports defenses against infection.'],spleen:['An organ high on the left side of your belly.','It filters blood and helps your immune system respond to some infections.'],thymus:['An immune-system organ behind the breastbone, especially active in childhood.','It helps some infection-fighting cells develop.'],uterus:['The womb, a hollow muscle-lined organ in the pelvis.','Its lining changes during the menstrual cycle, and it can support a pregnancy.'],ovaries:['Two small reproductive organs in the pelvis.','They release eggs and make hormones involved in menstrual cycles and reproduction.'],testes:['The organs inside the scrotum.','They make sperm and the hormone testosterone.'],prostate:['A small gland below the bladder, around the urine outlet.','It adds fluid to semen. Its position also means changes can affect urination.'],skin:['The body’s outer protective covering.','It helps keep germs out, limits water loss and lets you feel touch and temperature.']};
const advice:Record<System,[string,string,string]>={
 skeletal:['Build activity gradually, include strength and balance work suited to your ability, and reduce fall risks. Ask about safe exercise if you have fragile bones.','A fracture or joint injury can cause pain, reduced movement or difficulty bearing weight.','https://www.niams.nih.gov/health-topics/exercise-your-bone-health'],
 muscular:['Use gradual strength training, warm up before strenuous activity and allow recovery. Get persistent weakness or pain assessed.','Strained or weakened muscles can make everyday movements painful or difficult.','https://www.niams.nih.gov/health-topics/exercise-your-bone-health'],
 cardiovascular:['Stay active within your ability, avoid smoking and discuss blood pressure, cholesterol and blood sugar at routine checkups.','Poor blood flow or reduced pumping can leave tissues short of oxygen and can cause serious illness.','https://www.nhlbi.nih.gov/education/heart-truth/living-heart-healthy-lifestyle'],
 venous:['Move regularly and break up long periods of sitting. Seek medical advice for new unexplained swelling or pain.','Problems with blood return can cause swelling; a blood clot can be dangerous.','https://medlineplus.gov/vasculardiseases.html'],
 nervous:['Protect your head and back during risky activities, get adequate sleep and seek assessment for persistent numbness or weakness.','Damage can affect feeling, strength, coordination or the way organs are controlled. The effects depend on the location.','https://medlineplus.gov/neurologicdiseases.html'],
 respiratory:['Avoid tobacco smoke and harmful dust or fumes. Stay active as your breathing allows and discuss ongoing cough or breathlessness with a clinician.','Breathing problems can reduce oxygen delivery and make activity difficult.','https://medlineplus.gov/lungdiseases.html'],
 digestive:['Eat a varied diet, stay active and seek advice for persistent digestive changes. Avoid taking supplements or medicines as a way to “cleanse” an organ.','Problems may affect swallowing, digestion, nutrient absorption or passing waste, depending on the organ.','https://www.niddk.nih.gov/health-information/digestive-diseases'],
 sensory:['Use appropriate eye and hearing protection. Have persistent changes in sight, hearing, smell, taste or balance checked.','Injury can change how you sense your surroundings or affect balance and communication.','https://medlineplus.gov/anatomy.html'],
 urinary:['Manage blood pressure and diabetes if present, and ask about safe medicine use. Get urinary symptoms assessed rather than ignoring them.','Problems may affect waste removal or urine flow. Kidney disease can develop without obvious symptoms.','https://www.niddk.nih.gov/health-information/kidney-disease/chronic-kidney-disease-ckd/prevention'],
 endocrine:['Keep recommended checkups and follow prescribed treatment. Avoid taking hormone products without medical advice.','Hormone imbalance can affect energy, growth, blood sugar, blood pressure or reproduction.','https://medlineplus.gov/endocrinediseases.html'],
 lymphatic:['Follow recommended vaccinations and wound care. Have persistent or unexplained swelling assessed.','Problems can affect fluid drainage or immune defenses, depending on the structure.','https://medlineplus.gov/lymphaticdiseases.html'],
 reproductive:['Discuss screening, vaccination and sexual-health needs with your clinician. Have new lumps, unusual bleeding or persistent pelvic pain checked.','Problems can affect comfort, hormone levels, fertility or nearby urinary function, depending on the organ.','https://medlineplus.gov/reproductivehealth.html'],
 integumentary:['Protect skin from excessive sun, clean and care for wounds, and have changing skin lesions checked.','Damage can weaken the barrier against infection and affect comfort, feeling or temperature control.','https://medlineplus.gov/skininfections.html']};
export function education(part:Part,mesh?:MeshPart){
 const group=mesh?parts.find(p=>p.id===category(mesh)):part;
 const name=mesh?.name||part.name;
 const oblique=/external.*oblique|oblique.*external/i.test(name)&&part.system==='muscular'&&!/aponeurosis|tendon|fascia/i.test(name);
 const profile=group&&descriptions[group.id];
 const [care,systemHarm,systemSource]=advice[part.system];
 const side=/right/i.test(name)?'right':/left/i.test(name)?'left':null;
 const opposite=side==='right'?'left':'right';
 const what=oblique?`A broad muscle on ${side?'the '+side+' side':'each side'} of your belly, stretching from your lower ribs toward your pelvis.`:profile?.[0]||`${part.name} is part of the ${part.system} system. A structure-specific explanation has not yet been reviewed.`;
 const why=oblique?`It helps you bend sideways${side?' to the '+side:''}, turn your torso${side?' to the '+opposite:''}, and tighten your belly when coughing or lifting.`:profile?.[1]||'The information below describes the wider system, rather than a verified role for this individual piece.';
 const harm=oblique?'A strain can make twisting, coughing or sitting up painful along the side of your belly. Pain here can also come from other structures; location alone cannot identify the cause.':group?.id==='liver'?'Liver damage can affect processing of nutrients, blood clotting and removal of waste substances. Some liver diseases cause few symptoms early on; advanced disease may cause yellow skin or eyes, swelling or easy bruising.':systemHarm;
 const source=oblique?'https://www.ncbi.nlm.nih.gov/books/NBK525975/':group?.id==='liver'?'https://www.niddk.nih.gov/health-information/liver-disease':systemSource;
 return {what,why,care,harm,source,careSections:careSections(oblique?'abdominal':group?.id||'',part.system,care,systemSource),scope:oblique?null:mesh?(profile?`Learning about ${group!.name.toLowerCase()} · the group containing this selected piece`:'System-level overview'):null};
}
export const educationProfileIds=Object.keys(descriptions);
