'use client';
import {useEffect,useRef,useState} from 'react';
import {motion} from 'framer-motion';
import {Check,Download,Crosshair,RotateCcw} from 'lucide-react';
import {PainPoint} from './pain';
import {ChatLine,IntakeSession,emptyFacts,extractionSchema,fieldNames,intakeKey,labels,readIntake,patientFields} from './intake';
import VoiceControls from './VoiceControls';
import {staticSite} from './runtime';
import {groundedFacts,nextQuestion} from './intake';
import PatientIntake from './PatientIntake';
import {nextStep,reportedFacts} from './intakeFlow';
import {isClarificationAnswer} from './intakeDialogue';

const greeting='Where does it hurt, and what does it feel like?';
function newSession(sex:string):IntakeSession{return {id:crypto.randomUUID(),createdAt:new Date().toISOString(),patientIntakeStep:0,sex,messages:[{role:'assistant',content:greeting}],facts:emptyFacts(),stage:'describe',point:null,updatedAt:new Date().toISOString()};}
type Props={active:boolean;sex:string;point:PainPoint|null;onFocus:(area:string)=>void;onSuggest:(area:string)=>void;onRestorePoint:(point:PainPoint|null,sex?:string)=>void;onClear:()=>void;capture:()=>string};
export default function GuidedPain(props:Props){
 const [session,setSession]=useState<IntakeSession|null>(null),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[storageError,setStorageError]=useState(''),[snapshot,setSnapshot]=useState<string|null>(null),[exporting,setExporting]=useState(false),[clearConfirm,setClearConfirm]=useState(false),[danger,setDanger]=useState(false);
 const testMode=typeof window!=='undefined'&&new URLSearchParams(location.search).get('test')==='1';const storageKey=testMode?intakeKey+'.test':intakeKey;
 const latest=useRef(props);latest.current=props;const request=useRef<AbortController|null>(null);const loaded=useRef(false);const failedStorage=useRef(false);const scroll=useRef<HTMLDivElement>(null);const submitRef=useRef<(text?:string)=>void>(()=>{}),inputRef=useRef(''),autoTimer=useRef<ReturnType<typeof setTimeout>|null>(null);inputRef.current=input;
 useEffect(()=>{try{const saved=readIntake(localStorage.getItem(storageKey));setSession(saved||newSession(latest.current.sex));if(saved)latest.current.onRestorePoint(saved.point,saved.sex);}catch{failedStorage.current=true;setStorageError('The saved conversation could not be read and has not been overwritten. Clear it below to start saving again.');setSession(newSession(latest.current.sex));}loaded.current=true;return()=>{request.current?.abort();if(autoTimer.current)clearTimeout(autoTimer.current);};},[]);
 useEffect(()=>{if(!session||failedStorage.current)return;const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(session));setStorageError('');}catch{setStorageError('Your browser could not save this conversation. Keep this page open or download your summary.');}};save();window.addEventListener('pagehide',save);return()=>window.removeEventListener('pagehide',save);},[session]);
 useEffect(()=>{if(!loaded.current||!session||session.sex===props.sex)return;request.current?.abort();setBusy(false);setSnapshot(null);setSession(s=>s?{...s,sex:props.sex,point:null,stage:'describe'}:s);},[props.sex,session]);
 useEffect(()=>{if(!session||session.sex!==props.sex||JSON.stringify(session.point)===JSON.stringify(props.point))return;setSession(s=>s?{...s,point:props.point,stage:s.stage==='summary'?'confirm':s.stage}:s);setSnapshot(null);},[props.point,props.sex,session]);
 useEffect(()=>{if(!props.active&&autoTimer.current)clearTimeout(autoTimer.current);},[props.active]);
 useEffect(()=>{scroll.current?.scrollTo({top:scroll.current.scrollHeight,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[session?.messages.length,busy]);
 async function send(provided?:string){if(autoTimer.current)clearTimeout(autoTimer.current);if(!session||busy||!(provided??input).trim())return;const rawContent=(provided??input).trim();const clarified=isClarificationAnswer(session.messages,rawContent);const content=rawContent;const action=clarified?'extract':nextStep(session.stage,session.facts.region.value,!!props.point,content);if(action!=='extract'){setInput('');if(action==='confirm'){completeDescription();return;}if(action==='summary'){if(session.stage==='summary')return;await confirm();return;}setSession({...session,messages:[...session.messages,{role:'user',content},{role:'assistant',content:'Which body area should I record?'}]});return;}const messages:ChatLine[]=[...session.messages,{role:'user',content}];if(messages.length>58){setError('This conversation is full. Download your summary, then start a new conversation.');return;}setInput('');setError('');setSnapshot(null);latest.current.onClear();setSession(s=>s?{...s,messages,stage:'describe',locationConfirmed:false,point:null}:s);setBusy(true);const controller=new AbortController();request.current=controller;try{const response=staticSite?new Response(JSON.stringify((()=>{const facts=groundedFacts(emptyFacts(),messages);return {facts,reply:nextQuestion(facts,messages)};})()),{headers:{'Content-Type':'application/json'}}):await fetch('/api/pain-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages}),signal:controller.signal});const data=await response.json() as {error?:string;facts:unknown;reply:string};if(!response.ok)throw Error(data.error||'The assistant could not reply. Please retry.');const facts=extractionSchema.parse(data.facts);if(facts.region.value)latest.current.onSuggest(facts.region.value);setSession(s=>s?{...s,facts,messages:[...messages,{role:'assistant',content:data.reply}],updatedAt:new Date().toISOString()}:s);}catch(e){if(!controller.signal.aborted){setError(e instanceof Error?e.message:'Could not understand this message.');setInput(content);setSession(s=>s?{...s,messages:s.messages.slice(0,-1)}:s);}}finally{if(!controller.signal.aborted)setBusy(false);}}
 function completeDescription(){if(!session?.facts.region.value)return;const region=session.facts.region.value;setSession({...session,stage:'confirm',messages:[...session.messages,{role:'user',content:'I have nothing more to add for now.'},{role:'assistant',content:`Is the highlighted ${region.toLowerCase()} area correct? Confirm it, or add an exact pin.`}]});props.onSuggest(region);setSnapshot(null);}
 async function confirm(){if(!session||!session.facts.region.value)return;setError('');try{const image=props.capture();setSnapshot(image);const area=props.point?.region||session.facts.region.value;const side=props.point?.side||session.facts.side.value;const confirmation=`I confirm the ${props.point?'marked location':'highlighted area'}: ${side?side.toLowerCase()+' ':''}${area.toLowerCase()}.`;setSession({...session,facts:{...session.facts,region:{value:area,evidence:confirmation},side:side?{value:side,evidence:confirmation}:session.facts.side},point:props.point,locationConfirmed:true,stage:'summary',updatedAt:new Date().toISOString(),messages:[...session.messages,{role:'user',content:confirmation},{role:'assistant',content:'Your summary is ready.'}]});}catch(e){setError((e as Error).message);}}
 async function download(){if(!session||session.stage!=='summary')return;setExporting(true);setError('');try{const image=snapshot||props.capture();setSnapshot(image);const {createPatientPDF}=await import('./patientPdf');const pdf=await createPatientPDF(session,image);pdf.save('predoc-patient-summary.pdf');}catch(e){setError((e as Error).message||'Could not create the PDF. Please retry.');}finally{setExporting(false);}}
 function clear(){request.current?.abort();setBusy(false);try{localStorage.removeItem(storageKey);failedStorage.current=false;setStorageError('');}catch{setStorageError('This browser did not allow deleting the saved conversation.');return;}props.onClear();setSession(newSession(props.sex));setSnapshot(null);setInput('');setError('');setDanger(false);setClearConfirm(false);}
 submitRef.current=send;
 function dictated(text:string){const next=(inputRef.current+' '+text).trim().slice(0,4000);inputRef.current=next;setInput(next);if(autoTimer.current)clearTimeout(autoTimer.current);autoTimer.current=setTimeout(()=>submitRef.current(inputRef.current),2800);}
 function speechActivity(){if(autoTimer.current)clearTimeout(autoTimer.current);}
 if(!session)return <p className="storage-status">Opening your conversation…</p>;
 const intakeStep=session.patientIntakeStep??3;
 if(intakeStep<3)return <><PatientIntake key={intakeStep} step={intakeStep} patient={session.patient||{}} active={props.active&&!testMode} onChange={patient=>setSession(s=>s?{...s,patient,updatedAt:new Date().toISOString()}:s)} onNext={()=>setSession(s=>s?{...s,patientIntakeStep:Math.min(3,intakeStep+1),updatedAt:new Date().toISOString()}:s)} onBack={()=>setSession(s=>s?{...s,patientIntakeStep:Math.max(0,intakeStep-1)}:s)}/>{storageError&&<p className="storage-status">{storageError}</p>}</>;
 const stage=session.stage,region=session.facts.region.value,lastReply=[...session.messages].reverse().find(m=>m.role==='assistant')?.content||greeting;
 return <section className="guided-pain">{staticSite&&<p className="storage-status">Pages edition · basic symptom capture, not AI interpretation. Local AI and Microsoft voice require the local app.</p>}{testMode&&<p className="storage-status">Test session · separate from your saved notes · automatic microphone off</p>}<div className="intake-steps">{['Describe','Confirm','Summary'].map((name,i)=><span className={i===['describe','confirm','summary'].indexOf(stage)?'active':''} key={name}><b>{i+1}</b>{name}</span>)}</div>
 <div className="conversation-log" ref={scroll} role="log" aria-live="polite">{session.messages.slice(-2).map((m,i)=><motion.article key={i} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} className={'chat-'+m.role}><small>{m.role==='user'?'YOU':'ATLAS GUIDE'}</small><p>{m.content}</p></motion.article>)}{busy&&<p className="thinking">Understanding your description…</p>}</div>
 <VoiceControls active={props.active&&!testMode} text={lastReply} disabled={busy} onDictate={dictated} onSpeechActivity={speechActivity}/>
 <form className="chat-composer" onSubmit={e=>{e.preventDefault();send();}}><label htmlFor="symptom-message">{stage==='describe'?'Describe or add symptoms':'Add a correction or more detail'}</label><textarea id="symptom-message" value={input} onChange={e=>{speechActivity();setInput(e.target.value);}} onBlur={()=>{if(inputRef.current.trim()&&!busy)submitRef.current(inputRef.current);}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submitRef.current();}}} maxLength={4000} disabled={busy} placeholder="My lower back aches on the left. It started yesterday, about 4 out of 10…"/></form><small className="auto-submit-note">Speech sends after a short pause. For typing, press Enter or leave the field.</small>
 {error&&<p className="intake-error" role="alert">{error}</p>}
 {reportedFacts(session).length>0&&<section className="reported-symptoms"><h3>You reported</h3><ul>{reportedFacts(session).map(k=><li key={k}><span>{labels[k]}</span><strong>{session.facts[k].value}</strong></li>)}</ul><small>Only information from your conversation. Add a correction above if needed.</small></section>}
 {stage==='describe'&&region&&!busy&&!input.trim()&&<button className="primary-button" onClick={completeDescription}><Check size={16}/> Review location & summary</button>}
 {stage==='confirm'&&<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="location-review"><span className="eyebrow">DOES THIS LOOK RIGHT?</span><h3>{props.point?`${props.point.side} ${props.point.region.toLowerCase()}`:region}</h3><p>The glow shows reference anatomy in this area, not the cause of pain. Confirm this area, or optionally pin a more precise spot.</p><button className="primary-button" onClick={()=>props.onFocus(region||'Back')}><Crosshair size={16}/>{props.point?'Adjust exact spot':'Pin exact spot'}</button><button className="confirm-location" disabled={busy||!!input.trim()} onClick={confirm}><Check size={16}/> Yes, this is the area · create summary</button></motion.div>}
 {stage==='summary'&&<motion.div className="patient-summary" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><div className="summary-masthead"><span className="eyebrow">PATIENT-REPORTED</span><h3>Your symptom summary</h3><span>{new Date(session.updatedAt).toLocaleDateString()} · {session.sex} reference</span></div>{snapshot&&<img src={snapshot} alt="Snapshot of the confirmed pain location on the 3D reference atlas"/>}<p className="confirmed-location"><Check size={14}/> Confirmed {session.point?'pin':'area'}: {session.facts.side.value} {session.facts.region.value?.toLowerCase()}</p><dl>{reportedFacts(session).map(k=><div key={k}><dt>{labels[k]}</dt><dd>{session.facts[k].value||'Not reported'}{session.facts[k].evidence&&<small>“{session.facts[k].evidence}”</small>}</dd></div>)}</dl><details className="patient-details"><summary>Patient details & medical history (optional)</summary><p>Enter only information you know. Leaving a field blank means unknown, not “none”.</p>{Object.entries(patientFields).map(([key,label])=><label key={key}>{label}<input value={session.patient?.[key as keyof typeof patientFields]||''} maxLength={2000} onChange={e=>setSession({...session,patient:{...session.patient,[key]:e.target.value},updatedAt:new Date().toISOString()})}/></label>)}</details><p className="summary-footnote">AI-organized notes for review. The atlas is a reference model, not your scan. This report does not establish a diagnosis or rule out an emergency.</p><button className="primary-button" disabled={exporting||busy||!!input.trim()} onClick={download}><Download size={16}/>{exporting?'Preparing PDF…':'Download patient summary · PDF'}</button><button className="text-button" onClick={()=>{setSession({...session,stage:'confirm'});props.onSuggest(region||session.point?.region||'Back');}}>Review body location again</button></motion.div>}
 <details className="safety-guidance"><summary>When to seek urgent help</summary><p>For chest pain with breathlessness, fainting, or sudden weakness or speech trouble, seek emergency care. Back pain with new bladder or bowel changes, numbness around the genitals, or weakness in both legs also needs emergency care. Do not wait for this conversation.</p><a href="https://www.nhs.uk/conditions/back-pain/" target="_blank" rel="noreferrer">NHS back pain guidance ↗</a><label><input type="checkbox" checked={danger} onChange={e=>setDanger(e.target.checked)}/> I have an emergency symptom</label></details>{danger&&<div className="emergency" role="alert"><strong>Seek emergency care now.</strong><p>Call your local emergency number. Do not wait for a summary.</p></div>}
 <p className="storage-status">{storageError||(staticSite?'Saved on this device · basic symptom capture.':'Saved on this device · AI runs locally through Ollama.')}</p>{clearConfirm?<div className="clear-history"><p>Delete this conversation and start again? Earlier pain notes are managed separately below.</p><button onClick={clear}>Delete & start again</button><button onClick={()=>setClearConfirm(false)}>Cancel</button></div>:<button className="text-button" onClick={()=>setClearConfirm(true)}><RotateCcw size={13}/> New conversation / clear saved intake</button>}
 </section>;
}
