import {assetUrl} from './runtime';
import {parts,systems,Part,System} from './data';
export type MeshPart={id:string;name:string;conceptId:string;system:string;chunk:number;positions:number;normals:number;indices:number;vertexCount:number;indexCount:number;bounds:[number[],number[]]};
export type Atlas={parts:MeshPart[];chunks:{url:string;gzip:string;bytes:number}[];source:string;scope:string;triangles:number};
const promises:Record<string,Promise<Atlas>>={};
export function loadAtlas(sex:string){return promises[sex]??=(fetch(assetUrl(sex==='female'?'/models/atlas-female.json':'/models/atlas.json')).then(r=>{if(!r.ok)throw Error('The anatomy catalog could not load.');return r.json() as Promise<Atlas>;}).then(atlas=>({...atlas,parts:atlas.parts.filter(p=>p.system!=='pregnancy')})).catch(e=>{delete promises[sex];throw e;}));}
export function meshSystem(p:MeshPart):System{const map:Record<string,System>={arterial:'cardiovascular',cardiac:'cardiovascular',brain:'nervous',connective:'skeletal',borrowed:'skeletal','donor-muscle':'muscular',pregnancy:'reproductive'};return map[p.system]||p.system as System;}
export function category(p:MeshPart):string{
 const n=p.name.toLowerCase(),s=meshSystem(p);
 const patterns:[string,RegExp][]=[['heart',/heart|cardiac|ventricle|atrium|myocard|coronary/],['skull',/skull|cran|mandib|maxill|zygomatic|sphenoid|ethmoid|occipital bone|frontal bone|parietal bone|temporal bone|tooth|teeth|gingiva/],['clavicle',/clavicle|scapula/],['spine',/vertebra|intervertebral|sacrum|coccyx/],['ribs',/rib|sternum|costal|manubrium/],['pelvis',/ilium|ischium|pubis|hip bone|pelvis/],['humerus',/humerus/],['forearm',/radius|ulna/],['hand',/carpal|metacarp|phalanx of.*hand|finger|thumb/],['femur',/femur/],['patella',/patella/],['lowerleg',/tibia|fibula/],['foot',/tarsal|talus|calcaneus|foot|toe/],['pectoral',/pectoralis/],['deltoid',/deltoid/],['biceps',/biceps brachii|brachialis|triceps/],['quadriceps',/quadriceps|vastus|rectus femoris|sartorius|adductor/],['calf',/gastrocnemius|soleus|peroneus|tibialis/],['abdominal',/abdominis|abdominal/],['backmuscle',/trapezius|latissimus|erector|multifidus|rhomboid/],['brain',/brain|cerebr|cortex|gyrus|sulcus|thalam|pons|medulla|hippocamp/],['cord',/spinal cord/],['lungs',/lung|pulmonary alveol|lobule|lobe of.*lung/],['trachea',/trachea|bronch|larynx/],['diaphragm',/diaphragm/],['liver',/liver|hepatic|gallbladder/],['stomach',/stomach|gastric/],['intestines',/intestin|colon|ileum|jejunum|duoden|rectum|cecum|appendix/],['esophagus',/esophag/],['pancreas',/pancrea/],['eyes',/eye|retina|iris|cornea|lens|sclera|optic|ocular/],['ears',/ear|cochlea|vestibul|auditory|tympan/],['nose',/nose|nasal|olfactory/],['tongue',/tongue|lingual/],['kidneys',/kidney|renal|ureter/],['bladder',/bladder|urethra/],['thyroid',/thyroid/],['adrenals',/adrenal|suprarenal/],['pituitary',/pituitary/],['spleen',/spleen/],['thymus',/thymus/],['uterus',/uterus|uterine|vagina|vulva/],['ovaries',/ovary|ovaries|fallopian/],['testes',/testis|testes|penis|scrot|epididym|deferens/],['prostate',/prostate|seminal/]];
 if(p.system==='arterial')return 'arteries';if(p.system==='venous')return 'veins';if(p.system==='cardiac')return 'heart';if(p.system==='brain')return 'brain';
 for(const [id,re] of patterns){if(re.test(n)&&parts.find(x=>x.id===id)?.system===s)return id;}
 return ({skeletal:'',muscular:'',cardiovascular:'arteries',venous:'veins',nervous:'nerves',respiratory:'lungs',digestive:'intestines',sensory:'',urinary:'kidneys',endocrine:'',lymphatic:'lymph',reproductive:'',integumentary:'skin'} as Record<System,string>)[s];
}
export function describeMesh(p:MeshPart,sex:string):Part{const group=parts.find(x=>x.id===category(p)),s=meshSystem(p),sy=systems.find(x=>x[0]===s)!;const y=(p.bounds[0][1]+p.bounds[1][1])/2;const region=group?.region==='Whole body'?(y>1.48?'Head':y>1.35?'Neck':y>1.1?'Chest':y>.87?'Abdomen':y>.68?'Pelvis':'Leg'):group?.region||'Whole body';return {id:p.id,name:p.name,system:s,region,sex,description:isAdapted(p)?`${p.name} is adapted reference anatomy. ${p.system==='borrowed'?'This BodyParts3D male-derived bone was fitted to the female reference; it does not represent verified female bone shape.':'This lower-limb muscle is from a separate Visible Human Female donor and was fitted to this reference.'} Placement is approximate and has not been clinically validated.`:`${p.name} is an individually segmented structure in the ${sex==='male'?'BodyParts3D':'Human Reference Atlas'} reference.`,function:group?.function||('This structure belongs to the '+sy[1].toLowerCase()+' system, which supports '+sy[3].toLowerCase()+'. Explore it alongside surrounding structures for anatomical context.'),fact:group?.fact||'Use the layers to explore its relationship with surrounding structures.'};}

export function surfaceOpacity(name:string,visible:System[],opacity:number){return name.toLowerCase()==='skin'&&visible.some(s=>s!=='integumentary')?Math.min(.5,opacity/100):opacity/100;}

export function isAdapted(p:MeshPart){return p.system==='borrowed'||p.system==='donor-muscle';}
export function referenceParts(all:MeshPart[],adapted:boolean){return all.filter(p=>p.system!=='pregnancy'&&(adapted||!isAdapted(p)));}
export function provenance(p:MeshPart){return p.system==='borrowed'?'Adapted reference · male-derived bone':p.system==='donor-muscle'?'Adapted reference · separate female donor':'Source reference anatomy';}
