'use client';
import {useEffect,useState,useRef} from 'react';
import {PainDraft,PainConversation,PAIN_STORAGE_KEY,readPainStorage,painReply,detectPainRegion} from './pain';
type Props={restoreOnLoad?:boolean;draft:PainDraft;onRestore:(d:PainDraft)=>void;onFocus:(region:string)=>void;onClearPoint:()=>void};
export default function PainJournal({restoreOnLoad=true,draft,onRestore,onFocus,onClearPoint}:Props){
 const [conversations,setConversations]=useState<PainConversation[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[confirmClear,setConfirmClear]=useState(false);const restoreRef=useRef(onRestore);restoreRef.current=onRestore;const suppress=useRef(false);
 useEffect(()=>{try{const data=readPainStorage(localStorage.getItem(PAIN_STORAGE_KEY));setConversations(data.conversations);if(restoreOnLoad&&data.draft&&!location.hash)restoreRef.current(data.draft);setReady(true);}catch{setError('Saved history could not be read. It has not been overwritten. Clear saved history to start again.');}},[]);
 useEffect(()=>{if(!ready)return;if(suppress.current){suppress.current=false;return;}setSaved(false);const persist=()=>{try{localStorage.setItem(PAIN_STORAGE_KEY,JSON.stringify({version:1,draft,conversations}));setSaved(true);setError('');}catch{setError('This browser could not save your notes. Storage may be blocked or full.');}};const t=setTimeout(persist,250);window.addEventListener('pagehide',persist);return()=>{clearTimeout(t);window.removeEventListener('pagehide',persist);};},[draft,conversations,ready]);
 function send(){const current={...draft,region:draft.point?.region||detectPainRegion(draft.notes)||draft.region};onRestore(current);if(!current.point)onFocus(current.region);const now=new Date().toISOString(),id=crypto.randomUUID();const text=`${current.region}; ${current.quality}; ${current.severity}/10; ${current.duration}. ${current.notes}`;setConversations(items=>[{id,createdAt:now,draft:structuredClone(current),messages:[{id:id+'u',role:'user' as const,text,at:now},{id:id+'a',role:'assistant' as const,text:painReply(current),at:now}]},...items].slice(0,100));}
 function clear(){try{localStorage.removeItem(PAIN_STORAGE_KEY);suppress.current=true;setConversations([]);setSaved(false);setError('');setReady(true);setConfirmClear(false);restoreRef.current({...draft,notes:'',point:null,urgent:false});}catch{setError('This browser did not allow deleting local history.');}}
 const suggested=detectPainRegion(draft.notes);
 return <section className="pain-journal"><div className="point-controls"><h3>Pinpoint your pain</h3>{suggested&&suggested!==draft.region&&<button className="location-suggestion" onClick={()=>onFocus(suggested)}>Your note mentions {suggested.toLowerCase()} — zoom there ↗</button>}<button className="primary-button" onClick={()=>onFocus(suggested||draft.region)}>Point on body · {suggested||draft.region}</button><p>We’ll turn and zoom the body. Click or tap the exact spot; drag to adjust the view.</p>{draft.point&&<div className="point-summary"><strong>Marked: {draft.point.side} {draft.point.region.toLowerCase()}</strong><span>Patient-reported location, not a diagnosis</span><button onClick={onClearPoint}>Remove marker</button></div>}</div><button className="primary-button" onClick={send} disabled={!ready}>Save & get guidance</button><p className="storage-status" role="status">{error|| (saved?'Saved on this device.':'Notes and conversations are stored only in this browser.')} Anyone using this browser profile can access them.</p><details className="journal-history" open={conversations.length>0}><summary>Saved conversations ({conversations.length})</summary>{conversations.map(c=><article key={c.id}><header><span>{new Date(c.createdAt).toLocaleString()}</span><button aria-label="Delete saved conversation" onClick={()=>setConversations(items=>items.filter(x=>x.id!==c.id))}>Delete</button></header>{c.messages.map(m=><p key={m.id} className={'message-'+m.role}><strong>{m.role==='user'?'You':'Atlas guide'}</strong>{m.text}</p>)}<button onClick={()=>onRestore(c.draft)}>Restore notes & marker</button></article>)}</details>{confirmClear?<div className="clear-history"><p>Delete all saved pain conversations and current notes from this browser?</p><button onClick={clear}>Delete local history</button><button onClick={()=>setConfirmClear(false)}>Cancel</button></div>:<button className="clear-history-button" onClick={()=>setConfirmClear(true)}>Clear saved history & notes</button>}</section>;
}
