export type PainPoint={position:[number,number,number];sex:string;region:string;side:string;surfaceId:string};
export type PainMessage={id:string;role:'user'|'assistant';text:string;at:string};
export type PainDraft={sex:string;region:string;quality:string;severity:number;duration:string;notes:string;urgent:boolean;point:PainPoint|null};
export type PainConversation={id:string;createdAt:string;draft:PainDraft;messages:PainMessage[]};
export const PAIN_STORAGE_KEY='human-atlas.pain-conversations.v1';
export const painRegions=['Head','Neck','Shoulder','Chest','Upper back','Lower back','Back','Abdomen','Pelvis','Arm','Hand','Leg','Knee','Foot'];
export function detectPainRegion(text:string):string|null{const t=text.toLowerCase();if(/\b(lower\s*back|low\s*back|lumbar)\b/.test(t))return 'Lower back';if(/\b(upper\s*back|thoracic\s*back)\b/.test(t))return 'Upper back';return painRegions.find(r=>new RegExp('\\b'+r.toLowerCase()+'\\b').test(t))||null;}
export function validPoint(p:unknown):p is PainPoint{if(!p||typeof p!=='object')return false;const v=p as PainPoint;return ['male','female'].includes(v.sex)&&painRegions.includes(v.region)&&typeof v.surfaceId==='string'&&v.surfaceId.length<200&&['Left','Right','Midline'].includes(v.side)&&Array.isArray(v.position)&&v.position.length===3&&v.position.every(n=>typeof n==='number'&&Number.isFinite(n)&&Math.abs(n)<3);}
export function validDraft(d:unknown):d is PainDraft{if(!d||typeof d!=='object')return false;const v=d as PainDraft;return ['male','female'].includes(v.sex)&&painRegions.includes(v.region)&&['Aching','Sharp','Burning','Tingling','Throbbing','Cramping'].includes(v.quality)&&Number.isInteger(v.severity)&&v.severity>=1&&v.severity<=10&&['Today','1–3 days ago','Over a week ago','Recurring'].includes(v.duration)&&typeof v.notes==='string'&&v.notes.length<=2000&&typeof v.urgent==='boolean'&&(v.point===null||(validPoint(v.point)&&v.point.sex===v.sex));}
export function readPainStorage(value:string|null):{draft:PainDraft|null;conversations:PainConversation[]}{if(!value)return {draft:null,conversations:[]};const d=JSON.parse(value);if(d.version!==1||!Array.isArray(d.conversations)||d.conversations.length>100||!(d.draft===null||validDraft(d.draft)))throw Error('Unsupported or damaged pain history');for(const c of d.conversations){if(typeof c.id!=='string'||typeof c.createdAt!=='string'||!validDraft(c.draft)||!Array.isArray(c.messages)||c.messages.length>100||!c.messages.every((m:PainMessage)=>['user','assistant'].includes(m.role)&&typeof m.id==='string'&&typeof m.at==='string'&&typeof m.text==='string'&&m.text.length<=5000))throw Error('Invalid saved conversation');}return {draft:d.draft,conversations:d.conversations};}
export function painReply(d:PainDraft){if(d.urgent)return 'Seek emergency care now. Call your local emergency number; do not wait for this explorer.';const location=d.point?`${d.point.side.toLowerCase()} ${d.point.region.toLowerCase()}`:d.region.toLowerCase();return `You reported ${d.quality.toLowerCase()} pain at the ${location}, intensity ${d.severity}/10, starting ${d.duration.toLowerCase()}. ${d.point?'Your exact surface location is marked on the atlas.':'Use “Point on body” to mark the exact surface location.'} ${d.region==='Lower back'?'The lumbar spine, surrounding muscles, joints and nearby nerves are anatomy to explore. Pain can also be referred from elsewhere. ':''}${d.severity>=8?'Severe pain needs urgent medical assessment. ':''}This marks where you feel pain; it does not identify damaged tissue or diagnose a cause.`;}

export function classifyPainLocation(point:[number,number,number],minY:number,height:number,back:boolean){const y=(point[1]-minY)/height,x=Math.abs(point[0])/height;const side=Math.abs(point[0])<.025?'Midline':point[0]>0?'Left':'Right';let region:string;if(y>.87)region='Head';else if(y>.8)region='Neck';else if(x>.13&&y>.7)region='Shoulder';else if(x>.16&&y>.5)region='Arm';else if(x>.18&&y>.36)region='Hand';else if(y>.66)region=back?'Upper back':'Chest';else if(y>.53)region=back?'Lower back':'Abdomen';else if(y>.43)region='Pelvis';else if(y>.24&&y<.32)region='Knee';else if(y>.12)region='Leg';else region='Foot';return {region,side};}
