import {assetUrl} from './runtime';
import {jsPDF} from 'jspdf';
import {IntakeSession,fieldNames,labels,patientFields} from './intake';
export async function createPatientPDF(session:IntakeSession,snapshot:string,fontBase64?:string){
 if(session.stage!=='summary'||(!session.point&&!session.locationConfirmed))throw Error('Confirm your pain location before exporting.');
 const pdf=new jsPDF({unit:'mm',format:'a4'});let y=26;
 if(!fontBase64){const r=await fetch(assetUrl('/fonts/NotoSans-Regular.ttf'));if(!r.ok)throw Error('The report font could not load. Please retry.');const bytes=new Uint8Array(await r.arrayBuffer());let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);fontBase64=btoa(binary);}
 pdf.addFileToVFS('NotoSans.ttf',fontBase64);pdf.addFont('NotoSans.ttf','NotoSans','normal');pdf.addFont('NotoSans.ttf','NotoSans','bold');
 const clean=(s:string)=>s.replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[\u2013\u2014]/g,'-').replace(/[\x00-\x08\x0B-\x1F]/g,'');
 const header=()=>{pdf.setFillColor(15,35,61);pdf.rect(0,0,210,15,'F');pdf.setTextColor(144,198,255);pdf.setFontSize(9);pdf.setFont('NotoSans','bold');pdf.text('PREDOC  /  PATIENT SYMPTOM NOTES',16,9);};
 const page=()=>{pdf.addPage();header();y=26;};
 const line=(text:string,size=10,bold=false)=>{pdf.setFont('NotoSans',bold?'bold':'normal');pdf.setFontSize(size);pdf.setTextColor(34,52,61);const lines=pdf.splitTextToSize(clean(text),178) as string[];for(const row of lines){if(y>273)page();pdf.setFont('NotoSans',bold?'bold':'normal');pdf.setFontSize(size);pdf.setTextColor(34,52,61);pdf.text(row,16,y);y+=size*.46+1;}y+=2;};
 header();line('Your symptom summary',24,true);line(new Date(session.updatedAt).toLocaleString()+'  |  '+session.sex+' anatomy reference',9);line('Patient-reported location. Prepared for review, not a diagnosis.',10);
 const image=pdf.getImageProperties(snapshot);const width=Math.min(178,88*image.width/image.height),height=width*image.height/image.width;pdf.addImage(snapshot,'PNG',(210-width)/2,y,width,height);y+=height+7;
 line(session.point?`Confirmed pin: ${session.point.side} ${session.point.region.toLowerCase()}`:`Confirmed area: ${session.facts.side.value||''} ${session.facts.region.value||''} (no exact pin)`,12,true);line('3D reference atlas, not a patient scan. Highlighted anatomy does not establish the cause of pain.',8);
 for(const key of fieldNames){const fact=session.facts[key];if(!fact.value||!fact.evidence)continue;if(y>247)page();line(labels[key].toUpperCase(),8,true);line(fact.value||'Not reported',11);if(fact.evidence)line('Patient wording: "'+fact.evidence+'"',9);y+=2;}
 line('Patient details and medical background',16,true);for(const [key,label] of Object.entries(patientFields)){line(label,9,true);line(session.patient?.[key as keyof typeof patientFields]||'Unknown / not collected',10);}
 line('Record provenance',14,true);line('Record ID: '+session.id,9);line('Created: '+(session.createdAt||'Not recorded')+'; updated: '+session.updatedAt,9);line('Source: patient conversation and user-entered details. Prepared automatically by PreDoc, with location confirmation by the user. Identity is not verified. No healthcare-professional author or clinical verification is available.',9);
 line('Original conversation',16,true);for(const m of session.messages){line(m.role==='user'?'PATIENT':'ATLAS GUIDE',8,true);line(m.content,10);}
 line('Reference and scope',14,true);line('Informed by eHealth Network Patient Summary Guidelines, release 3.4 (November 2024). This is a limited patient-generated symptom report, not a conformant cross-border clinical Patient Summary. Blank history fields indicate missing information, not negative findings. No coded clinical exchange, identity authentication or healthcare-professional signature is provided.',9);if(y>265)page();pdf.textWithLink('eHealth Network Patient Summary guidelines',16,y,{url:'https://health.ec.europa.eu/system/files/2023-10/ehn_guidelines_patientsummary_en.pdf'});y+=9;line('AI-organized notes reviewed through location confirmation. Unreported details remain unknown. This educational tool cannot diagnose, identify damaged tissue, or rule out emergencies.',9);line('Geometry: BodyParts3D / Human Reference Atlas, CC BY 4.0. Female atlas coverage is partial and can include adapted reference geometry. Attribution: /ATTRIBUTION.md in the local app.',8);
 const count=pdf.getNumberOfPages();for(let p=1;p<=count;p++){pdf.setPage(p);pdf.setDrawColor(209,219,221);pdf.line(16,283,194,283);pdf.setFontSize(8);pdf.setTextColor(93,111,119);pdf.text('PRIVATE - patient-reported symptom record',16,289);pdf.text(`${p} / ${count}`,194,289,{align:'right'});}return pdf;
}
