import {assetUrl} from './runtime';
'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {motion,AnimatePresence} from 'framer-motion';
import {PainPoint,classifyPainLocation} from './pain';
import {System} from './data';
import {loadAtlas,meshSystem,category,MeshPart,surfaceOpacity,isAdapted} from './model';
type Props={captureRef:{current:(()=>string)|null};painArea:string|null;sex:string;visible:System[];selected:string;opacity:number;rotate:boolean;view:string;reset:number;zoom:number;onSelect:(id:string)=>void;pin:boolean;adapted:boolean;painPoint:PainPoint|null;painFocus:{region:string;nonce:number}|null;marking:boolean;onMark:(point:PainPoint)=>void};
const colors:Record<string,string>={skeletal:'#ded6c4',connective:'#b3ac94',muscular:'#a83d36',arterial:'#d34144',cardiac:'#b13742',venous:'#4c78c7',nervous:'#e2b866',brain:'#d6b0a4',respiratory:'#cc9894',digestive:'#c18c75',sensory:'#abb9b0',urinary:'#ad6577',endocrine:'#e7b475',lymphatic:'#7eaa81',reproductive:'#c8869c',integumentary:'#c2a08c',borrowed:'#a3b4c9','donor-muscle':'#b66b69',pregnancy:'#c8869c'};
export default function Scene(props:Props){
 const host=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;const [error,setError]=useState(''),[progress,setProgress]=useState(0),[ready,setReady]=useState(false),[hover,setHover]=useState('');
 const previousZoom=useRef(props.zoom);
 const cameraGoal=useRef<THREE.Vector3|null>(null),sceneRef=useRef<{camera:THREE.PerspectiveCamera;controls:OrbitControls;root:THREE.Group;bounds:THREE.Box3}|null>(null);
 useEffect(()=>{if(!host.current)return;setProgress(0);setReady(false);setError('');let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{setError('WebGL is unavailable. Try a browser with hardware acceleration. The anatomy list remains available.');return;}
 let disposed=false;const controller=new AbortController(),el=host.current;renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),root=new THREE.Group();scene.add(root);const camera=new THREE.PerspectiveCamera(32,1,.01,100);camera.position.set(0,.05,17.7);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=2;controls.maxDistance=28;controls.autoRotateSpeed=.45;controls.addEventListener('start',()=>{cameraGoal.current=null;});
 scene.add(new THREE.HemisphereLight(0xe6efff,0x35323b,1.8));const key=new THREE.DirectionalLight(0xffebda,3.5);key.position.set(-3,6,7);scene.add(key);const fill=new THREE.DirectionalLight(0xd4e7ff,1.8);fill.position.set(4,1,5);scene.add(fill);const rim=new THREE.DirectionalLight(0x97d0de,2.5);rim.position.set(2,4,-5);scene.add(rim);
 const meshes:THREE.Mesh[]=[];const sourceBounds=new THREE.Box3();sceneRef.current={camera,controls,root,bounds:sourceBounds};
 const marker=new THREE.Mesh(new THREE.SphereGeometry(.012,18,12),new THREE.MeshBasicMaterial({color:'#ff714c',depthTest:false}));marker.renderOrder=999;marker.visible=false;root.add(marker);
 const isVisible=(m:THREE.Mesh)=>latest.current.visible.includes(m.userData.system)&&(latest.current.adapted||!m.userData.adapted);
 const updateMesh=(m:THREE.Mesh)=>{const p=latest.current;const area=p.painArea;const f=area?({'Head':[.87,1],'Neck':[.8,.87],'Shoulder':[.7,.8],'Chest':[.66,.8],'Upper back':[.66,.8],'Back':[.53,.8],'Lower back':[.53,.66],'Abdomen':[.53,.66],'Pelvis':[.43,.53],'Arm':[.5,.7],'Hand':[.36,.5],'Leg':[.12,.43],'Knee':[.24,.32],'Foot':[0,.12]} as Record<string,number[]>)[area]:null;const y=(m.userData.centerY-sourceBounds.min.y)/(sourceBounds.max.y-sourceBounds.min.y);const nearby=!!f&&y>=f[0]&&y<=f[1];const selected=p.pin&&area?nearby:m.userData.id===p.selected||m.userData.category===p.selected;const mat=m.material as THREE.MeshStandardMaterial;m.visible=isVisible(m);mat.opacity=surfaceOpacity(m.userData.name,p.visible,p.opacity);mat.side=m.userData.name.toLowerCase()==='skin'?THREE.FrontSide:THREE.DoubleSide;mat.depthWrite=mat.opacity>.8;mat.color.set(selected?(p.pin?'#ff985b':'#9e84ff'):(colors[m.userData.source]||'#bfa896'));mat.emissive.set(selected?(p.pin?'#d85a18':'#653dff'):'#000000');mat.emissiveIntensity=selected?.45:0;};
 (async()=>{try{const data=await loadAtlas(props.sex);if(disposed)return;const allBounds=new THREE.Box3();data.parts.filter(p=>p.system!=='pregnancy').forEach(p=>{allBounds.expandByPoint(new THREE.Vector3(...p.bounds[0] as [number,number,number]));allBounds.expandByPoint(new THREE.Vector3(...p.bounds[1] as [number,number,number]));});sourceBounds.copy(allBounds);const center=allBounds.getCenter(new THREE.Vector3()),size=allBounds.getSize(new THREE.Vector3());root.scale.setScalar(8.6/size.y);root.position.copy(center).multiplyScalar(-8.6/size.y);
 const add=(p:MeshPart,buffer:ArrayBuffer)=>{const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(buffer,p.positions,p.vertexCount*3),3));geo.setAttribute('normal',new THREE.BufferAttribute(new Int16Array(buffer,p.normals,p.vertexCount*3),3,true));geo.setIndex(new THREE.BufferAttribute(new Uint32Array(buffer,p.indices,p.indexCount),1));geo.computeBoundingSphere();const mat=new THREE.MeshStandardMaterial({color:colors[p.system]||'#bfa896',roughness:p.system==='skeletal'?.56:.47,metalness:.03,transparent:true,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geo,mat);mesh.userData={id:p.id,name:p.name,system:meshSystem(p),source:p.system,category:category(p),adapted:isAdapted(p),centerY:(p.bounds[0][1]+p.bounds[1][1])/2};updateMesh(mesh);root.add(mesh);meshes.push(mesh);};
 let done=0,next=0;const worker=async()=>{while(next<data.chunks.length&&!disposed){const index=next++,chunk=data.chunks[index];if(!data.parts.some(p=>p.chunk===index)){done++;continue;}const r=await fetch(assetUrl(chunk.gzip),{signal:controller.signal});if(!r.ok)throw Error('An anatomical model file could not load. Please reload to retry.');const raw=await r.arrayBuffer();const bytes=new Uint8Array(raw);let buffer=raw;if(bytes[0]===31&&bytes[1]===139){if(!('DecompressionStream'in window))throw Error('This browser cannot decompress the anatomy. Please use a current browser.');buffer=await new Response(new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();}if(disposed)return;data.parts.filter(p=>p.chunk===index).forEach(p=>add(p,buffer));done++;setProgress(Math.round(done/data.chunks.length*100));}};await Promise.all([worker(),worker(),worker()]);if(!disposed){setReady(true);setProgress(100);props.captureRef.current=()=>{if(cameraGoal.current)throw Error("The camera is still moving. Wait a moment, then try again.");renderer.setClearColor(0x101b24,1);renderer.render(scene,camera);const image=renderer.domElement.toDataURL("image/png");renderer.setClearColor(0,0);return image;};}}
 catch(e){if(!disposed){controller.abort();setError(e instanceof Error?e.message:'The anatomy could not load. Reload to retry.');}}})();
 const resize=()=>{const {width,height}=el.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();
 const ray=new THREE.Raycaster();let down=[0,0],lastHover=0;const intersect=(e:PointerEvent,skinOnly=false)=>{const rect=el.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);return ray.intersectObjects(meshes.filter(m=>skinOnly?m.userData.name.toLowerCase()==='skin':m.visible&&!(m.userData.name.toLowerCase()==='skin'&&latest.current.visible.some(s=>s!=='integumentary'))),false)[0];};
 const pointerDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const p=latest.current;const hit=intersect(e,p.marking);if(hit&&p.marking){const point=root.worldToLocal(hit.point.clone());const extent=sourceBounds.getSize(new THREE.Vector3());const location=classifyPainLocation(point.toArray() as [number,number,number],sourceBounds.min.y,extent.y,camera.position.z<controls.target.z);p.onMark({position:point.toArray() as [number,number,number],sex:p.sex,region:location.region,side:location.side,surfaceId:hit.object.userData.id});}else if(hit)p.onSelect(hit.object.userData.id);};const pointerMove=(e:PointerEvent)=>{if(e.buttons||performance.now()-lastHover<90)return;lastHover=performance.now();const hit=intersect(e);setHover(hit?hit.object.userData.name+(hit.object.userData.adapted?' · Adapted reference':''):'');el.style.cursor=hit?'pointer':'grab';};const leave=()=>setHover('');
 renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointermove',pointerMove);renderer.domElement.addEventListener('pointerleave',leave);
 let frame=0,lastState='';const animate=()=>{frame=requestAnimationFrame(animate);const p=latest.current,reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;controls.autoRotate=p.rotate&&!reduced;if(cameraGoal.current){camera.position.lerp(cameraGoal.current,reduced?1:.075);if(camera.position.distanceTo(cameraGoal.current)<.005)cameraGoal.current=null;}controls.update();marker.visible=!!p.painPoint&&p.painPoint.sex===p.sex;if(marker.visible)marker.position.fromArray(p.painPoint!.position);const state=[p.visible.join(),p.selected,p.opacity,p.pin,p.adapted,p.painArea].join('|');if(state!==lastState){meshes.forEach(updateMesh);lastState=state;}renderer.render(scene,camera);};animate();
 return()=>{props.captureRef.current=null;disposed=true;controller.abort();cancelAnimationFrame(frame);observer.disconnect();controls.dispose();marker.geometry.dispose();(marker.material as THREE.Material).dispose();meshes.forEach(m=>{m.geometry.dispose();(m.material as THREE.Material).dispose();});renderer.dispose();renderer.domElement.remove();sceneRef.current=null;};
 },[props.sex]);
 useEffect(()=>{const s=sceneRef.current;if(!s)return;s.controls.target.set(0,0,0);const angle=props.view==='Back'?Math.PI:props.view==='Side'?Math.PI/2:0;cameraGoal.current=new THREE.Vector3(Math.sin(angle)*17.7,.05,Math.cos(angle)*17.7);},[props.view,props.reset,props.sex]);
 useEffect(()=>{const s=sceneRef.current;if(!s)return;const delta=props.zoom-previousZoom.current;previousZoom.current=props.zoom;if(!delta)return;const offset=(cameraGoal.current||s.camera.position).clone().sub(s.controls.target);cameraGoal.current=offset.setLength(Math.max(2,Math.min(28,offset.length()*Math.pow(.82,delta)))).add(s.controls.target);},[props.zoom]);
 useEffect(()=>{const s=sceneRef.current;if(!s||!ready||!props.painFocus)return;const area=props.painFocus.region;const height=s.bounds.max.y-s.bounds.min.y;const fractions:Record<string,number>={'Head':.92,'Neck':.82,'Shoulder':.77,'Chest':.72,'Upper back':.73,'Back':.66,'Lower back':.59,'Abdomen':.59,'Pelvis':.47,'Arm':.62,'Hand':.46,'Leg':.27,'Knee':.28,'Foot':.055};let local=new THREE.Vector3(0,s.bounds.min.y+height*(fractions[area]||.6),s.bounds.getCenter(new THREE.Vector3()).z);if(props.painPoint?.sex===props.sex&&props.painPoint.region===area)local.fromArray(props.painPoint.position);const target=s.root.localToWorld(local);s.controls.target.copy(target);const back=/back/i.test(area);cameraGoal.current=target.clone().add(new THREE.Vector3(0,.1,back?-4.4:4.4));},[props.painFocus,ready,props.sex]);
 return <div className="scene" ref={host} aria-label="Detailed human anatomy. Drag to rotate, scroll to zoom, and select a structure."><AnimatePresence>{!ready&&!error&&<motion.div className="asset-loading" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><span className="loading-orbit"/><strong>Loading {props.sex} reference</strong><span>Reconstructing anatomical layers · {progress}%</span><div className="loading-track"><motion.i animate={{width:progress+'%'}}/></div></motion.div>}</AnimatePresence>{error&&<div className="scene-error"><strong>Model unavailable</strong><p>{error}</p><button onClick={()=>location.reload()}>Retry loading</button></div>}{hover&&ready&&<div className="hover-structure">{hover}</div>}</div>;
}
