'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {motion,AnimatePresence} from 'framer-motion';
import {System} from './data';
import {loadAtlas,meshSystem,category,MeshPart} from './model';
type Props={sex:string;visible:System[];selected:string;opacity:number;rotate:boolean;view:string;reset:number;zoom:number;onSelect:(id:string)=>void;pin:boolean;supplement:boolean};
const colors:Record<string,string>={skeletal:'#ded6c4',connective:'#b3ac94',muscular:'#a83d36',arterial:'#d34144',cardiac:'#b13742',venous:'#4c78c7',nervous:'#e2b866',brain:'#d6b0a4',respiratory:'#cc9894',digestive:'#c18c75',sensory:'#abb9b0',urinary:'#ad6577',endocrine:'#e7b475',lymphatic:'#7eaa81',reproductive:'#c8869c',integumentary:'#c2a08c',borrowed:'#a3b4c9','donor-muscle':'#b66b69',pregnancy:'#c8869c'};
export default function Scene(props:Props){
 const host=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;const [error,setError]=useState(''),[progress,setProgress]=useState(0),[ready,setReady]=useState(false),[hover,setHover]=useState('');
 const cameraGoal=useRef<THREE.Vector3|null>(null),sceneRef=useRef<{camera:THREE.PerspectiveCamera;controls:OrbitControls}|null>(null);
 useEffect(()=>{if(!host.current)return;setProgress(0);setReady(false);setError('');let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{setError('WebGL is unavailable. Try a browser with hardware acceleration. The anatomy list remains available.');return;}
 let disposed=false;const controller=new AbortController(),el=host.current;renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),root=new THREE.Group();scene.add(root);const camera=new THREE.PerspectiveCamera(32,1,.01,100);camera.position.set(0,.05,17.7);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=2;controls.maxDistance=28;controls.autoRotateSpeed=.45;controls.addEventListener('start',()=>{cameraGoal.current=null;});
 scene.add(new THREE.HemisphereLight(0xe6efff,0x35323b,1.8));const key=new THREE.DirectionalLight(0xffebda,3.5);key.position.set(-3,6,7);scene.add(key);const fill=new THREE.DirectionalLight(0xd4e7ff,1.8);fill.position.set(4,1,5);scene.add(fill);const rim=new THREE.DirectionalLight(0x97d0de,2.5);rim.position.set(2,4,-5);scene.add(rim);
 const meshes:THREE.Mesh[]=[];sceneRef.current={camera,controls};
 const isVisible=(m:THREE.Mesh)=>latest.current.visible.includes(m.userData.system)&&((m.userData.source!=='borrowed'&&m.userData.source!=='donor-muscle')||latest.current.supplement)&&m.userData.source!=='pregnancy';
 const updateMesh=(m:THREE.Mesh)=>{const p=latest.current;const selected=m.userData.id===p.selected||m.userData.category===p.selected;const mat=m.material as THREE.MeshStandardMaterial;m.visible=isVisible(m);mat.opacity=m.userData.source==='integumentary'?.13:p.opacity/100;mat.depthWrite=mat.opacity>.8;mat.emissive.set(selected?(p.pin?'#f15b35':'#34c9bc'):'#000000');mat.emissiveIntensity=selected?.27:0;};
 (async()=>{try{const data=await loadAtlas(props.sex);if(disposed)return;const allBounds=new THREE.Box3();data.parts.filter(p=>p.system!=='pregnancy').forEach(p=>{allBounds.expandByPoint(new THREE.Vector3(...p.bounds[0] as [number,number,number]));allBounds.expandByPoint(new THREE.Vector3(...p.bounds[1] as [number,number,number]));});const center=allBounds.getCenter(new THREE.Vector3()),size=allBounds.getSize(new THREE.Vector3());root.scale.setScalar(8.6/size.y);root.position.copy(center).multiplyScalar(-8.6/size.y);
 const add=(p:MeshPart,buffer:ArrayBuffer)=>{const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(buffer,p.positions,p.vertexCount*3),3));geo.setAttribute('normal',new THREE.BufferAttribute(new Int16Array(buffer,p.normals,p.vertexCount*3),3,true));geo.setIndex(new THREE.BufferAttribute(new Uint32Array(buffer,p.indices,p.indexCount),1));geo.computeBoundingSphere();const mat=new THREE.MeshStandardMaterial({color:colors[p.system]||'#bfa896',roughness:p.system==='skeletal'?.56:.47,metalness:.03,transparent:true,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geo,mat);mesh.userData={id:p.id,name:p.name,system:meshSystem(p),source:p.system,category:category(p)};updateMesh(mesh);root.add(mesh);meshes.push(mesh);};
 let done=0,next=0;const worker=async()=>{while(next<data.chunks.length&&!disposed){const index=next++,chunk=data.chunks[index];const r=await fetch(chunk.gzip,{signal:controller.signal});if(!r.ok)throw Error('An anatomical model file could not load. Please reload to retry.');const raw=await r.arrayBuffer();const bytes=new Uint8Array(raw);let buffer=raw;if(bytes[0]===31&&bytes[1]===139){if(!('DecompressionStream'in window))throw Error('This browser cannot decompress the anatomy. Please use a current browser.');buffer=await new Response(new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();}if(disposed)return;data.parts.filter(p=>p.chunk===index).forEach(p=>add(p,buffer));done++;setProgress(Math.round(done/data.chunks.length*100));}};await Promise.all([worker(),worker(),worker()]);if(!disposed){setReady(true);setProgress(100);}}
 catch(e){if(!disposed){controller.abort();setError(e instanceof Error?e.message:'The anatomy could not load. Reload to retry.');}}})();
 const resize=()=>{const {width,height}=el.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();
 const ray=new THREE.Raycaster();let down=[0,0],lastHover=0;const intersect=(e:PointerEvent)=>{const rect=el.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);return ray.intersectObjects(meshes.filter(m=>m.visible&&m.userData.source!=='integumentary'),false)[0];};
 const pointerDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const hit=intersect(e);if(hit)latest.current.onSelect(hit.object.userData.id);};const pointerMove=(e:PointerEvent)=>{if(e.buttons||performance.now()-lastHover<90)return;lastHover=performance.now();const hit=intersect(e);setHover(hit?.object.userData.name||'');el.style.cursor=hit?'pointer':'grab';};const leave=()=>setHover('');
 renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointermove',pointerMove);renderer.domElement.addEventListener('pointerleave',leave);
 let frame=0,lastState='';const animate=()=>{frame=requestAnimationFrame(animate);const p=latest.current,reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;controls.autoRotate=p.rotate&&!reduced;if(cameraGoal.current){camera.position.lerp(cameraGoal.current,reduced?1:.075);if(camera.position.distanceTo(cameraGoal.current)<.005)cameraGoal.current=null;}controls.update();const state=[p.visible.join(),p.selected,p.opacity,p.pin,p.supplement].join('|');if(state!==lastState){meshes.forEach(updateMesh);lastState=state;}renderer.render(scene,camera);};animate();
 return()=>{disposed=true;controller.abort();cancelAnimationFrame(frame);observer.disconnect();controls.dispose();meshes.forEach(m=>{m.geometry.dispose();(m.material as THREE.Material).dispose();});renderer.dispose();renderer.domElement.remove();sceneRef.current=null;};
 },[props.sex]);
 useEffect(()=>{const s=sceneRef.current;if(!s)return;s.controls.target.set(0,0,0);const angle=props.view==='Back'?Math.PI:props.view==='Side'?Math.PI/2:0;cameraGoal.current=new THREE.Vector3(Math.sin(angle)*17.7,.05,Math.cos(angle)*17.7);},[props.view,props.reset,props.sex]);
 useEffect(()=>{const s=sceneRef.current;if(!s)return;cameraGoal.current=s.camera.position.clone().sub(s.controls.target).setLength(Math.max(2,17.7-props.zoom*1.6)).add(s.controls.target);},[props.zoom]);
 return <div className="scene" ref={host} aria-label="Detailed human anatomy. Drag to rotate, scroll to zoom, and select a structure."><AnimatePresence>{!ready&&!error&&<motion.div className="asset-loading" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><span className="loading-orbit"/><strong>Loading {props.sex} reference</strong><span>Reconstructing anatomical layers · {progress}%</span><div className="loading-track"><motion.i animate={{width:progress+'%'}}/></div></motion.div>}</AnimatePresence>{error&&<div className="scene-error"><strong>Model unavailable</strong><p>{error}</p><button onClick={()=>location.reload()}>Retry loading</button></div>}{hover&&ready&&<div className="hover-structure">{hover}</div>}</div>;
}
