'use client';
import {staticSite} from './runtime';
import {useEffect,useRef,useState} from 'react';
import {Mic,Volume2,Square} from 'lucide-react';
import {Recognition,startDictation} from './dictation';
export default function VoiceControls({active,text,onDictate,onSpeechActivity,disabled}:{active:boolean;text:string;onDictate:(s:string)=>void;onSpeechActivity:()=>void;disabled:boolean}){
 const [listening,setListening]=useState(false),[playing,setPlaying]=useState(false),[error,setError]=useState(''),[interim,setInterim]=useState(''),[status,setStatus]=useState('');
 const latest=useRef({onDictate,onSpeechActivity,active,disabled});latest.current={onDictate,onSpeechActivity,active,disabled};const recognizer=useRef<ReturnType<typeof startDictation>|null>(null),audio=useRef<HTMLAudioElement|null>(null),request=useRef<AbortController|null>(null),sequence=useRef(0);
 function stop(preserveFinal=false){sequence.current++;request.current?.abort();if(preserveFinal)recognizer.current?.stop();else{recognizer.current?.dispose();recognizer.current=null;}if(audio.current){audio.current.pause();URL.revokeObjectURL(audio.current.src);audio.current=null;}setListening(false);setPlaying(false);setInterim('');setStatus('');}
 function listen(){if(!latest.current.active||latest.current.disabled)return;const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const C=w.SpeechRecognition||w.webkitSpeechRecognition;if(!C){setError('This browser does not support dictation. Use Chrome or Edge, or type below.');return;}recognizer.current=startDictation(C,{onFinal:s=>latest.current.onDictate(s),onInterim:s=>{setInterim(s);if(s)latest.current.onSpeechActivity();},onListening:setListening,onError:setError});}
 async function start(read=true){stop();setError('');const ticket=sequence.current;try{if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('Microphone access requires localhost or HTTPS in a supported browser.');setStatus('Checking microphone permission…');try{const p=await navigator.permissions?.query({name:'microphone' as PermissionName});if(p?.state==='denied')throw Error('Microphone access is blocked. Allow it in this site’s browser permissions, then press Start voice.');}catch(e){if(e instanceof Error&&e.message.startsWith('Microphone access is blocked'))throw e;}if(ticket!==sequence.current)return;const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());if(ticket!==sequence.current)return;setStatus('');if(staticSite||!read||!text){listen();return;}setPlaying(true);const controller=new AbortController();request.current=controller;const response=await fetch('/api/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text}),signal:controller.signal});if(!response.ok)throw Error('Voice playback is unavailable. Press the microphone to dictate, or type below.');const url=URL.createObjectURL(await response.blob());if(ticket!==sequence.current){URL.revokeObjectURL(url);return;}const a=new Audio(url);audio.current=a;a.onended=()=>{URL.revokeObjectURL(url);audio.current=null;setPlaying(false);if(ticket===sequence.current)listen();};a.onerror=()=>{setPlaying(false);setError('Audio playback failed. Press the microphone or type below.');};await a.play();}catch(e){if(ticket!==sequence.current)return;setPlaying(false);setStatus('');const name=e instanceof Error?e.name:'';setError(name==='NotAllowedError'?'Microphone or audio playback permission is needed. Allow microphone access, then press Start voice.':name==='NotFoundError'?'No microphone was found. Connect one or type below.':e instanceof Error?e.message:'Could not start voice. Type below or retry.');}}
 useEffect(()=>{if(active&&!disabled)void start();else stop();return()=>{sequence.current++;request.current?.abort();recognizer.current?.dispose();if(audio.current){audio.current.pause();URL.revokeObjectURL(audio.current.src);audio.current=null;}};},[active,disabled,text]);
 return <div className="voice-session"><div className={'voice-orb '+(listening?'is-listening':'')}><Mic size={24}/></div><strong>{listening?'Listening…':playing?'Speaking…':status||'Ready when you are'}</strong><div className="voice-actions"><button disabled={disabled} onClick={()=>{if(listening||playing||status){stop(true);}else void start();}}>{listening||playing||status?<Square size={15}/>:<Volume2 size={15}/>} {listening||playing||status?'Stop voice':'Start voice'}</button><button disabled={disabled||listening} aria-label="Start microphone without read aloud" onClick={()=>void start(false)}><Mic size={16}/></button></div>{interim&&<p className="dictation-interim">{interim}</p>}{error&&<p className="voice-error" role="alert">{error}</p>}<details><summary>Voice & privacy</summary><p>Replies use Microsoft online speech. Your browser may process dictation online. Symptom understanding runs on this computer. You can stop voice and type at any time.</p></details></div>;
}
