import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),cache={};
function load(name){if(cache[name])return cache[name];const file=new URL('../app/atlas/'+name+'.ts',import.meta.url);const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const mod={exports:{}};vm.runInNewContext(source,{exports:mod.exports,module:mod,require:n=>n.startsWith('./')?load(n.slice(2)):require(n),fetch,Uint8Array,btoa,Date,console});return cache[name]=mod.exports;}
const flow=load('intakeFlow');assert.equal(flow.nextStep('describe','Lower back',false,'yes please proceed'),'confirm');assert.equal(flow.nextStep('confirm','Lower back',false,'yes'),'summary');assert.equal(flow.nextStep('summary','Lower back',false,'proceed'),'summary');assert.equal(flow.nextStep('describe',null,false,'proceed'),'ask-location');assert.equal(flow.nextStep('describe','Back',false,'do not proceed'),'extract');assert.equal(flow.nextStep('describe','Back',false,'it also burns'),'extract');
assert.equal(flow.nextStep('describe','Lower back',false,'I confirm that I want it to proceed'),'confirm');
const i=load('intake');const facts=i.emptyFacts();facts.region={value:'Lower back',evidence:'left lower back'};facts.side={value:'Left',evidence:'left'};facts.quality={value:'Lumbar strain',evidence:'aches'};facts.severity={value:'7',evidence:'seven out of ten'};
const messages=[{role:'user',content:'My left lower back aches since yesterday.'}];const safe=i.groundedFacts(facts,messages);assert.equal(safe.region.value,'Lower back');assert.equal(safe.quality.value,'aches');assert.equal(safe.severity.value,null);assert.equal(safe.onset.value,null);const invented=i.emptyFacts();invented.severity={value:'10',evidence:'excruciating lower back pain'};assert.equal(i.groundedFacts(invented,[{role:'user',content:'excruciating lower back pain'}]).severity.value,null);assert.equal(i.groundedFacts(i.emptyFacts(),[{role:'user',content:'four out of ten'}]).severity.value,'4');
assert.throws(()=>i.groundedFacts({...facts,diagnosis:'strain'},messages));
const session={id:'test',sex:'female',messages,facts:safe,stage:'summary',point:{position:[.03,.9,-.1],sex:'female',region:'Lower back',side:'Left',surfaceId:'skin'},updatedAt:'2026-09-10T12:00:00.000Z'};
assert.equal(i.readIntake(JSON.stringify(session)).point.region,'Lower back');assert.equal(i.readIntake(JSON.stringify({...session,point:null,locationConfirmed:true})).locationConfirmed,true);assert(!flow.reportedFacts(session).includes('severity'));
const ed=load('education'),data=load('data'),model=load('model');assert(data.parts.every(p=>ed.educationProfileIds.includes(p.id)));const coverage={};for(const file of ['atlas.json','atlas-female.json']){const a=JSON.parse(fs.readFileSync('public/models/'+file));const meshes=model.referenceParts(a.parts,true);let specific=0;for(const m of meshes){const p=model.describeMesh(m,file.includes('female')?'female':'male');const e=ed.education(p,m);assert(e.what&&e.why&&e.care&&e.harm&&e.source);if(ed.educationProfileIds.includes(model.category(m)))specific++;}coverage[file]={meshes:meshes.length,groupProfiles:specific,systemOverviews:meshes.length-specific};}console.log('Education coverage',coverage);assert.throws(()=>i.readIntake(JSON.stringify({...session,point:null})));assert.throws(()=>i.readIntake('{'));assert.throws(()=>i.readIntake(JSON.stringify({...session,point:{...session.point,sex:'male'}})));

// Synthetic image fixture validates the PDF layout; it is not a patient atlas capture.
const sharp=require('/Users/abhinavjha/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const png=await sharp(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="800" height="600" fill="#101b24"/><circle cx="400" cy="300" r="50" fill="#d87550"/><text x="400" y="400" fill="#f0f6f3" text-anchor="middle" font-size="24">SNAPSHOT LAYOUT FIXTURE</text></svg>')).png().toBuffer();
const {createPatientPDF}=load('patientPdf');const font=fs.readFileSync(new URL('../public/fonts/NotoSans-Regular.ttf',import.meta.url)).toString('base64');
const pdf=await createPatientPDF(session,'data:image/png;base64,'+png.toString('base64'),font);assert(pdf.getNumberOfPages()>=2);fs.mkdirSync('tmp/pdfs',{recursive:true});fs.writeFileSync('tmp/pdfs/intake-test.pdf',Buffer.from(pdf.output('arraybuffer')));
await assert.rejects(()=>createPatientPDF({...session,stage:'confirm'},'',font));
const regional=await createPatientPDF({...session,point:null,locationConfirmed:true},'data:image/png;base64,'+png.toString('base64'),font);assert(regional.getNumberOfPages()>0);
console.log('Proceed transitions, area-only confirmation, reported-only facts, education coverage, grounded extraction, unsupported-fact rejection, unknown fields, saved-session validation, local conversation and PDF export checks passed.');
